Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-04, with the labels that each got.

#1840 Allow the product options process to be more extensible in the JSON data it sends to the page
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionsProcessor.java
Labels: type-enhancement

#1841 Add a convenience method for the final price (considering sale prices) onto Product
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Product.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
Labels: type-enhancement

#1842 Send a 404 instead of a 500 response when static assets cannot be found from the underlying storage system
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/file/StaticAssetViewController.java
Labels: type-enhancement

#1839 Translation links are broken when page type is changing
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-minor, type-bug

#1844 Allow an input to manually specify that its changes should be tracked on modification in the admin
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm-status.js
Labels: module-admin, type-enhancement

#1845 Update to the latest patch versions of Spring and Spring Boot, 4.3.15.RELEASE and 1.5.11.RELEASE
  pom.xml
Labels: module-core, type-enhancement

#1846 Delegate to the Spring Boot default multipart limits for file uploads
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/web/controller/AdminMultipartUploadConfig.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/web/controller/NonAutoconfigMultiPartConfiguration.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetStorageServiceImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/file/StaticAssetViewController.java
  admin/broadleaf-contentmanagement-module/src/main/resources/config/bc/cms/common.properties
Labels: type-enhancement

#1847 Simplified Product Option Validation so that it's easier to understand
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/add/ValidateAddRequestActivity.java
Labels: module-core, type-enhancement

#1850 Error removing a child order item from the cart
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/AddWorkflowPriceOrderIfNecessaryActivity.java
Labels: severity-major, type-bug

#1838 Pasting Text into an HTML field in the admin does not trigger the save button to be enabled
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm-status.js
Labels: severity-minor, type-bug

#1830 Fix Google Analytics Processor to be compatible with non-discrete order items
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/GoogleUniversalAnalyticsProcessor.java
Labels: type-bug

#1849 Address issue where entities where getting incorrectly their updated date changed when browsing the site
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/audit/AdminAuditableListener.java
Labels: severity-major, type-bug

#1673 Sku#getMultiValueSkuAttributes has inaccurate return type
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Sku.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
Labels: severity-major, type-bug

#1817 Cache misses on pages that cannot be found for the given URL
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/service/PageServiceImpl.java
Labels: type-enhancement

#1814 Show the exclamation point icon with error description
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/partials/listGridIcon.html
Labels: module-admin, severity-minor, type-bug

#1855 Non-discrete order item attributes and child items are not copied over when creating an item request from an existing order item
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
Labels: severity-minor, target-5.2.4-GA, type-bug

#1858 CSRF token exception is not handled by Spring Boot error handling when deploying as a .war file
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/filter/AdminSecurityFilter.java
  common/src/main/java/org/broadleafcommerce/common/security/handler/SecurityFilter.java
Labels: type-enhancement

#1859 Disallow adding archived skus to cart
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductOptionDaoImpl.java
Labels: type-bug

#1708 Enhance pageField map to allow programatic maintenance
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageFieldImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/CMSFormBuilderExtensionHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
Labels: severity-minor, type-enhancement

#1862 Fixed bug where rules based on Locale couldn't be promoted
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/rulebuilder/service/OrderFieldServiceImpl.java
Labels: severity-minor, target-5.2.4-GA, type-bug

#1811 Catch all Payment Type Variable Expression made public
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/expression/checkout/PaymentMethodVariableExpression.java
Labels: type-enhancement

#1861 Allow structured content field map to have better programmatic maintenance
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/web/service/CMSFormBuilderExtensionHandler.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentFieldImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentFieldXrefImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
Labels: target-5.1.9-GA, target-5.2.4-GA, type-enhancement

#1863 Handle Spring 4.3.16 bean creation changes in tests
  integration/src/test/java/org/broadleafcommerce/common/workflow/DummyProcessContextFactory.java
  integration/src/test/java/org/broadleafcommerce/common/workflow/ExceptionActivity.java
  integration/src/test/java/org/broadleafcommerce/common/workflow/NestedActivity.java
  integration/src/test/java/org/broadleafcommerce/common/workflow/RollbackTest.java
  integration/src/test/java/org/broadleafcommerce/common/workflow/SimpleActivity.java
  integration/src/test/java/org/broadleafcommerce/common/workflow/SimpleRollbackHandler.java
  integration/src/test/resources/bl-applicationContext-test.xml
Labels: severity-major, type-bug

#1853 Add methods to skip cache when retrieving order, fix potential synchronization problems with sending order persisted events
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderPersistedEntityListener.java
Labels: severity-minor, type-bug

#1864 Use error level logging when error occurs in checkout flow
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafCheckoutController.java
Labels: severity-medium, type-enhancement

#1827 Added the ability to use the Google Closure Compiler
  common/pom.xml
  common/src/main/java/org/broadleafcommerce/common/config/BroadleafCommonConfig.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/CssMinificationService.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/GoogleClosureJavascriptMinificationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/JavascriptMinificationService.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceMinificationException.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceMinificationService.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceMinificationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/YUICssMinificationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/YUIJavascriptMinificationServiceImpl.java
  common/src/main/resources/config/bc/common.properties
  pom.xml
Labels: severity-medium, type-enhancement

#1865 Fixed OfferPriceData matching process to correctly evaluate SKU_EXTERNAL_ID
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableOfferUtilityImpl.java
Labels: severity-minor, type-bug

#1869 Provide a convenience method for obtaining the topmost production clone ID in a multitenant hierarchy
  common/src/main/java/org/broadleafcommerce/common/sandbox/DefaultSandBoxHelper.java
  common/src/main/java/org/broadleafcommerce/common/sandbox/SandBoxHelper.java
Labels: type-enhancement

#1871 fix admin JS edit filter errors caused when subRules are undefined
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/query-builder.js
Labels: target-5.2.4-GA
