Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-11, with the labels that each got.

#2012 Remove collection alias' from SolrQuery in favor of executing commands on a collection
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Indexable.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/BroadleafCloudSolrClient.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrConfiguration.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/GlobalSolrFullReIndexOperation.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexOperation.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexServiceImpl.java
Labels: severity-medium, type-bug

#1971 Forcing Admin images extension to be lowercase
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/processor/UrlRewriteProcessor.java
Labels: severity-minor, type-bug

#1761 Introduce logging to warn against incorrect page/item management for StreamCapableTransactionalOperations
  common/src/main/java/org/broadleafcommerce/common/util/StreamingTransactionCapableUtil.java
Labels: type-enhancement

#1707 Enhanced FieldDefinition fields with `@AdminPresentation` so that they could be overridden, and added more field types to DynamicSupportedFieldTypes enumeration so that more basic fields are available in the admin.
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldDefinition.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldDefinitionImpl.java
  common/src/main/java/org/broadleafcommerce/common/presentation/client/DynamicSupportedFieldType.java
Labels: type-enhancement

#2018 Added "Locale" row in BLC_ADMIN_SECTION
  core/broadleaf-framework/src/main/resources/config/bc/sql/load_admin_menu.sql
Labels: type-bug

#1984 Fix for incorrect reference to tabs when using href to get elements of the tab
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
Labels: severity-minor, type-bug

#2013 Set ActiveID cookie to secure out-of-the-box
  common/src/main/resources/config/bc/common.properties
Labels: type-enhancement

#2020 Handle empty date fields in the admin
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
Labels: severity-major, type-bug
