Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-06, with the labels that each got.

#1907 Fix ClassCastException in the RatingsProcessor
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/RatingsProcessor.java
Labels: severity-medium, type-bug

#1706 ReferenceSite - If cart has errors validated during checkout, user gets redirected to login page instead of displaying error message
  common/src/main/java/org/broadleafcommerce/common/web/payment/controller/PaymentGatewayAbstractController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafCheckoutController.java
Labels: severity-minor, target-5.2.3-GA, type-bug

#1905 Changed the Google Closure Compiler artifact to the unshaded version
  common/pom.xml
  common/src/main/java/org/broadleafcommerce/common/resource/service/GoogleClosureJavascriptMinificationServiceImpl.java
  pom.xml
Labels: type-bug

#1908 Added missing admin presentation on fulfillmentOption fields
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/FulfillmentOptionImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/fulfillment/domain/FixedPriceFulfillmentOptionImpl.java
Labels: severity-critical, target-5.2.5-GA, type-bug

#1912 Introduce Minimum Order Quantity Validation for Skus
  admin/broadleaf-admin-module/src/main/resources/admin_style/js/admin/catalog/skuMinOrderQuantity.js
  admin/broadleaf-admin-module/src/main/resources/bl-admin-applicationContext.xml
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/GreaterThanMinValueValidator.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuMinOrderQuantity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/WeaveSkuMinOrderQuantity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/add/ValidateAddRequestActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/service/OrderItemRequestValidationService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/service/OrderItemRequestValidationServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/update/ValidateUpdateRequestActivity.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext.xml
  core/broadleaf-framework/src/test/groovy/org/broadleafcommerce/core/spec/order/service/workflow/add/ValidateAddRequestActivitySpec.groovy
Labels: type-feature

#1913 Add dependentFieldHandler for defaultSku's min order quantity fields in the Admin
  admin/broadleaf-admin-module/src/main/resources/admin_style/js/admin/catalog/skuMinOrderQuantity.js
Labels: severity-minor, type-bug

#1915 Add externalId to Customer core domain
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityProfile.properties
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerDao.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerDaoImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/Customer.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/CustomerAdminPresentation.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/CustomerImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/service/CustomerServiceImpl.java
Labels: migration-required, type-feature

#1910 Remove YUICompressor Javascript minification support
  common/pom.xml
  common/src/main/java/org/broadleafcommerce/common/resource/service/GoogleClosureJavascriptMinificationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceMinificationService.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceMinificationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/YUIJavascriptMinificationServiceImpl.java
  common/src/main/resources/config/bc/common.properties
  pom.xml
Labels: type-enhancement

#1919 fix search with non default locale
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/catalog/BroadleafCategoryController.java
Labels: type-bug

#1921 fix offer does not apply when edited by a CSR
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/core/CustomerStateRefresher.java
Labels: type-bug

#1922 Added more exception context when an EntityNotFoundException occurs
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/AdminEntityServiceImpl.java
Labels: type-enhancement

#1924 Page Translations are not evicted from the cache when deploying changes to the site
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/service/PageQueryExtensionManager.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/service/PageServiceImpl.java
Labels: severity-medium, type-bug

#1914 Fixed issue where the RuleBuilder Selectize Component was not loading additional rows from the server beyond the original initialized list
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
Labels: severity-major, target-5.2.5-GA, type-bug

#1925 Normalized uploaded file assets to lowercase the extension
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetServiceImpl.java
Labels: severity-minor, type-bug

#1926 Fixed archived search facet ranges not being filtered out
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/dao/SearchFacetDaoImpl.java
Labels: severity-medium, target-5.2.5-GA, type-bug

#1923 Fix PostgreSQL Clob error with custom PostgreSQLDialect
  common/src/main/java/org/broadleafcommerce/common/dialect/BroadleafPostgreSQLDialect.java
  common/src/main/java/org/broadleafcommerce/common/dialect/PostgreSQLClobTypeDescriptor.java
Labels: severity-critical, target-6.0.0-GA, type-bug

#1917 Convert Hibernate's deprecated session.createCriteria() with JPA criteria
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BasicFieldMetadataProvider.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductOptionDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/dto/AssignedProductOptionDTO.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferDaoImpl.java
Labels: severity-medium, target-6.0.0-GA

#1927 Add AdminPresentation annotations to reviews domain
  admin/broadleaf-admin-module/src/main/resources/messages/MerchandisingMessages.properties
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/domain/RatingDetailImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/domain/RatingSummaryImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/domain/ReviewDetailImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/domain/ReviewFeedbackImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/service/type/RatingSortType.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/service/type/RatingType.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/service/type/ReviewStatusType.java
Labels: module-admin, type-enhancement

#1928 Revert "BroadleafCommerce/QA#3310 - initial commit to fix the alternate theme…"
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafRequestProcessor.java
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/core/security/CustomerStateRequestProcessor.java
Labels: severity-critical, target-5.2.5-GA, type-bug

#1929 Overrode default Hibernate naming strategies
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/JPAPropertiesPersistenceUnitPostProcessor.java
Labels: severity-critical, type-bug

#1931 Update Spring, Spring Boot and Spring Security versions to 4.3.18, 1.5.14 and 4.2.7
  pom.xml
Labels: module-core, type-enhancement

#1932 Update to Spring 5.0.7, Boot 2.0.3, Spring Security 5.0.6 and Jackson 2.9.6
  pom.xml
Labels: module-core, type-enhancement

#1933 BroadleafCommerce/QA#3403 - Evict environment prefixed cache key
  common/src/main/java/org/broadleafcommerce/common/config/service/SystemPropertiesServiceImpl.java
Labels: severity-medium, type-bug

#1930 Added explicit join column names where missing
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
Labels: type-enhancement

#1937 Added minimum quantity exception and removed error logging
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/exception/MinQuantityNotFulfilledException.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/add/ValidateAddRequestActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/update/ValidateUpdateRequestActivity.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-workflow.xml
Labels: severity-medium, type-bug

#1936 Reenable save button after to-one selection
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm-status.js
Labels: target-6.0.0-GA, type-bug

#1934 Consider the super class when obtaining a property iterator from Hibernate metadata
  common/src/main/java/org/broadleafcommerce/common/util/dao/HibernateMappingProvider.java
Labels: affects-6.0.0-M1, module-admin, severity-major, type-bug

#1939 Multiple Validation Errors Creating a Product Breaks Selecting a Category
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: severity-medium, target-5.2.5-GA, type-bug

#1935 Fix issue where multiple bundles with same name get the same file lists
  common/src/main/java/org/broadleafcommerce/common/web/processor/AbstractResourceProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/ResourceBundleProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/request/ResourcesRequest.java
  common/src/main/java/org/broadleafcommerce/common/web/request/ResourcesRequestBundle.java
Labels: target-5.2.5-GA, type-bug

#1942 6.0 Community Uploading a large asset causes generic error message
  common/src/main/java/org/broadleafcommerce/common/exception/FileUploadExceptionAdvice.java
Labels: type-bug

#1943 Added functionality to combine the indexes defined on the weave class with the target classes @Table annotation
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/copy/DirectCopyClassTransformer.java
Labels: severity-major, type-bug

#1944 Added null check for order when DatabaseOrderLockManager is configured to throw exception instead of queueing the lock attempt
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/order/DatabaseOrderLockManager.java
Labels: severity-medium, type-bug

#1951 Added null check when ValidateAddActivity evaluates the order currency
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/add/ValidateAddRequestActivity.java
Labels: severity-minor, type-bug
