Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-03, with the labels that each got.

#1809 Addressed issue where rules where failing to evaluate when using the APIs
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/core/security/RestApiCustomerStateFilter.java
Labels: severity-critical, type-bug

#1808 Filter facets that only have zero results
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
Labels: type-enhancement

#1813 Adding more parameters to SearchCriteria
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/service/SearchFacetDTOServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchCriteria.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
Labels: target-5.2.4-GA, type-enhancement

#1818 Allow the search criteria created from the FacetDTOService to be pluggable
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/service/SearchFacetDTOServiceImpl.java
Labels: module-core, type-enhancement

#1819 Ensure that item attributes and child items are copied over for non-discrete order items when going from wishlists to carts
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
Labels: module-core, severity-minor, target-5.1.9-GA, type-bug

#1822 Offer Validation and Rulebuilder Errors
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/blc-query-builder.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm-status.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/blc-admin-query-builder.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/utility/error.html
Labels: type-bug

#1825 Fixed and refactored LDAP admin user provisioning to better handle mapping of roles/authorities
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/user/AdminUserProvisioningServiceImpl.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/service/SearchFacetDTOServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
Labels: severity-medium, type-bug

#1820 Modal's tabs are not populated when modal displays more then once
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/ui/modal.js
Labels: severity-medium, target-5.2.4-GA, type-bug

#1831 Limit image uploads in the admin to 2MB
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetStorageServiceImpl.java
Labels: type-feature

#1828 Translation links in modals were not getting enabled
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
Labels: severity-minor, type-bug

#1832 Fixed issue where Solr delete queries did not filter out non-product documents
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexServiceImpl.java
Labels: severity-medium, type-bug

#1833 Ensure that the max image upload check is case insensitive when checking the file extension
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetStorageServiceImpl.java
Labels: severity-medium, type-bug

#1829 Add the current page to the meta title
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/head.html
Labels: severity-minor, type-bug

#1815 Using @Resource to resolve the fileExtensionWhitelist dependency in ProcompressedArtifactFilter
  common/src/main/java/org/broadleafcommerce/common/web/util/PrecompressedArtifactFilter.java
Labels: severity-minor, type-bug

#1835 Improve i18n support in the admin
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/partials/entityFormFields.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/views/collectionListGrid.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/views/modal/adornedSelectEntity.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/views/modal/simpleSelectEntity.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/views/modal/translationListGrid.html
Labels: type-enhancement

#1836 Re-add RTL support to Redactor after the library was upgrade
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
Labels: type-bug

#1742 IgnoreSite state can be left on the BroadleafRequestContext for static asset related calls
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/dao/StaticAssetDaoImpl.java
Labels: severity-major, type-bug

#1603 Added PriceAdjustments to the ProductOptionDTO in ProductOptionsProcessor
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionsProcessor.java
Labels: type-enhancement
