Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-05, with the labels that each got.

#1870 Modal's tabs are not populated when modal displays more then once
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: severity-medium, target-5.2.4-GA, type-bug

#1872 Ensure the confirm password field is ordered directly after the password
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/PasswordFieldMetadataProvider.java
Labels: severity-minor, type-bug

#1873 Ensure that dynamic forms in the admin respect field ordering in their field definitions
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/server/handler/DynamicFieldPersistenceHandlerHelper.java
Labels: module-admin, severity-minor, type-bug

#1876 Validation not happening on dynamic forms (pages and structured content)
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/server/handler/PageTemplateCustomPersistenceHandler.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/server/handler/StructuredContentTypeCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorService.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: module-admin, severity-major, type-bug

#1878 Always keep translations disabled on adds
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/fieldTranslation.html
Labels: module-admin, type-enhancement

#1874 Enable creating SystemEvents without a dependency on the ScheduledJobsAndEvents module
  common/src/main/java/org/broadleafcommerce/common/event/BroadleafSystemEvent.java
  common/src/main/java/org/broadleafcommerce/common/event/BroadleafSystemEventDetail.java
Labels: type-feature

#1875 Fixed issue where the query cache wasn't invalidated when OMS updated sku inventory
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/InventoryServiceImpl.java
Labels: type-bug

#1881 Fixes the issue where adding condition on cart rules break the page.
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
Labels: severity-minor, type-bug

#1882 URL encode square brackets to support Tomcat 8.5.31 regression
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/service/SearchFacetDTOServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchFacetResultDTO.java
Labels: type-bug, type-enhancement

#1883 Add a helper class to support setting QueryHints across Hibernate 4.1 and 5.2
  common/src/main/java/org/broadleafcommerce/common/persistence/HibernateBridgingQueryHints.java
Labels: type-enhancement

#1885 Resolve the StaticAssetView immediately from the asset controller without going through the view resolver chain
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/file/StaticAssetViewController.java
Labels: type-enhancement

#1886 Fix UseShippingAddress for mixed Shippable/Nonshippable orders
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafPaymentInfoController.java
Labels: type-bug

#1889 Add Support for the Java bin RequestWriter during Solr indexing
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
Labels: type-enhancement

#1890 Upgrade Solr client to 7.3.0 and remove remaining support for Sku indexing via solr.index.use.sku
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/catalog/ProductHandlerMapping.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/catalog/SkuHandlerMapping.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/cart/BroadleafCartController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/catalog/BroadleafCategoryController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/catalog/BroadleafSearchController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/UncacheableDataProcessor.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/workflow/ValidateProductOptionsActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/add/ValidateAddRequestActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchResult.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/BroadleafCloudSolrClient.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrConfiguration.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexServiceImpl.java
  core/broadleaf-framework/src/main/resources/config/bc/fw/common.properties
  core/broadleaf-framework/src/test/groovy/org/broadleafcommerce/core/spec/checkout/service/workflow/ValidateProductOptionsActivitySpec.groovy
  core/broadleaf-framework/src/test/groovy/org/broadleafcommerce/core/spec/search/service/solr/SolrIndexServiceSpec.groovy
  pom.xml
Labels: migration-recommended, type-feature

#1893 Fixed an incompatible cast in the equals method of ProratedOrderItemAdjustmentImpl
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/ProratedOrderItemAdjustmentImpl.java
Labels: severity-medium, type-bug

#1900 Bundle Dependency Management Enhancements and Preloading
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceBundlingService.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceBundlingServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/AbstractResourceProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/ResourceBundleProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/ResourcePreloadProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/attributes/ResourceTagAttributes.java
  common/src/main/java/org/broadleafcommerce/common/web/request/ResourcesRequest.java
Labels: target-5.2.5-GA, type-enhancement
