Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-08, with the labels that each got.

#1965 Dependency version updates (Spring Boot to 1.5.15, Lombok and Groovy to the latest)
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/DynamicEntityDaoImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/user/AdminUserDetails.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/FieldManager.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CrossSaleProduct.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/UpSaleProduct.java
  pom.xml
Labels: module-core, type-enhancement

#1966 Dependency version updates - (Spring to 5.0.8, Spring Boot to 2.0.4, Spring Security to 5.0.7)
  pom.xml
Labels: type-enhancement

#1967 Upgrade framework library due to security vulnerabilities
  pom.xml
Labels: type-security

#1968 Fixed the offer code with named "$item" that can not be stored in a cookie
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferCodeImpl.java
Labels: target-5.2.6-GA, type-bug

#1895 Offer start and end dates not applied correctly if admin user TZ is different than server TZ
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/BasicFieldPersistenceProvider.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/AbstractBaseProcessor.java
Labels: target-5.2.5-GA, type-bug

#1973 Add an extension point to add query params to selectize request
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
Labels: type-enhancement
