Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-07, with the labels that each got.

#1948 Cleaned up AdminUserDetails, Service, and AdminProvisioningService
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/user/AdminUserDetails.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/user/AdminUserDetailsServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/user/AdminUserProvisioningServiceImpl.java
Labels: target-5.2.5-GA, target-5.3.0-GA, type-enhancement

#1906 Upgrade framework libraries due to security vulnerabilities
  admin/broadleaf-admin-functional-tests/pom.xml
  admin/broadleaf-admin-module/pom.xml
  admin/broadleaf-contentmanagement-module/pom.xml
  admin/broadleaf-open-admin-platform/pom.xml
  admin/broadleaf-open-admin-platform/src/main/resources/applicationContext-servlet-open-admin.xml
  admin/pom.xml
  common/pom.xml
  core/broadleaf-framework-web/pom.xml
  core/broadleaf-framework/pom.xml
  core/broadleaf-profile-web/pom.xml
  core/broadleaf-profile/pom.xml
  core/pom.xml
  integration/pom.xml
  pom.xml
Labels: type-security

#1957 Change `receiveEmail` on Customers to default to `false`
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/CustomerImpl.java
Labels: type-enhancement

#1958 Add `FulfillmentGroupItem`s for any child `OrderItems`
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/FulfillmentGroupServiceImpl.java
Labels: severity-major, type-bug

#1959 OrderMultishipOption's OrderItem's children aren't added to fulfillment groups
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/FulfillmentGroupServiceImpl.java
Labels: severity-major, type-bug

#1952 Updated EntityDuplicator domain to be more generic and extinsible
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminOfferController.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminProductController.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/web/controller/AdminAssetUploadController.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminAbstractController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminTranslationController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicOperationsController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/entity/DefaultEntityFormActions.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/entity/EntityFormAction.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/dao/GenericEntityDaoImpl.java
  common/src/main/java/org/broadleafcommerce/common/persistence/AbstractEntityDuplicationHelper.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicateModifier.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicationHelper.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicator.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorImpl.java
  common/src/test/resources/blc-config/bl-test-applicationContext.xml
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferDuplicateModifier.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext.xml
Labels: target-5.3.0-GA, type-enhancement

#1956 Performance improvements for building metadata
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/DynamicEntityDaoImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/FieldManager.java
Labels: module-admin, type-enhancement

#1954 Generic Foldering Feature
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/CriteriaTransferObject.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/AdminSectionHrefProcessor.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/domain/PersistencePackageRequest.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminSection.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminSectionImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/extension/AdminSecurityCheckExtensionHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/extension/AdminSecurityCheckExtensionManager.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/remote/AdminSecurityServiceRemote.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/AdminEntityServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/extension/CriteriaTransferObjectExtensionHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/extension/CriteriaTransferObjectExtensionManager.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/component/ListGrid.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/blc-admin.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/entityForm.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-filter.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/searchFields.html
Labels: type-feature

#1963 Clear the FieldManager's middle fields on a call to `getFieldManager()`
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/DynamicEntityDaoImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/FieldManager.java
Labels: severity-critical, type-bug
