Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-02, with the labels that each got.

#1786 Allow an EntityForm to contain file upload inputs
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/entity/EntityForm.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm-status.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
Labels: module-admin, type-enhancement

#1787 Added ability to handle extended map entity xrefs through the admin
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/MapStructurePersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: severity-minor, type-bug

#1789 Allow passed in arguments to have precedence over blSelectize defaults
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
Labels: type-enhancement

#1791 Added support for Offers restricted to max uses by account
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/BasicFieldMetadata.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/fields/broadleaf_enumeration.html
  common/src/main/java/org/broadleafcommerce/common/presentation/AdminPresentation.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferAuditDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferAuditDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/Offer.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferAdminPresentation.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferAudit.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferAuditImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferAuditService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferAuditServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/type/CustomerMaxUsesStrategyType.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/workflow/RecordOfferUsageActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/workflow/VerifyCustomerMaxOfferUsesActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/NullOrderImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/Order.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderImpl.java
Labels: migration-required, type-enhancement

#1785 Allow content targeting against arbitrary http request cookie values
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/config/AdminWebConfig.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/rulebuilder/service/extension/CookieFieldServiceExtensionHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/DataDTOToMVELTranslator.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/config/FrameworkWebConfig.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/cookie/CookieRuleFilter.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/cookie/CookieRuleRequestProcessor.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rule/RuleDTOConfig.java
Labels: severity-minor, type-enhancement

#1783 Admin Offer Enhancements
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminOfferController.java
  admin/broadleaf-admin-module/src/main/resources/messages/UtilityMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/ui/messages_en.js
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopyContext.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicateModifier.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicator.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorExtensionManager.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferDuplicateModifier.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
Labels: severity-minor, type-enhancement

#1792 Added Order and OrderItem Methods to support Export module
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/SkuDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/CatalogService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/CatalogServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderItemDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderItemDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
Labels: type-enhancement

#1799 Added support for setting map values to null through fields such as custom fields
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/AbstractFieldPersistenceProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/FieldPersistenceProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/MapFieldPersistenceProvider.java
Labels: severity-major, type-bug

#1805 Added support for fieldComponentRendererTemplate on AdminPresentation
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/BasicFieldMetadata.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/override/FieldMetadataOverride.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BasicFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/presentation/AdminPresentation.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/PropertyType.java
Labels: type-enhancement

#1802 Enhanced Offer engine to support listed price discounts
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/persistence/validation/OfferTargetItemCriteriaValidator.java
  admin/broadleaf-admin-module/src/main/resources/admin_style/js/admin/catalog/offer.js
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/fields/hidden_boolean.html
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Product.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/Offer.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferPriceData.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferPriceDataImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceUtilities.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceUtilitiesImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/CandidatePromotionItems.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableCandidateFulfillmentGroupOffer.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableCandidateFulfillmentGroupOfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableCandidateItemOffer.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableCandidateItemOfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableFulfillmentGroupAdjustment.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableFulfillmentGroupAdjustmentImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableItemFactoryImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableOfferUtility.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableOfferUtilityImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableOrderItemPriceDetailAdjustmentImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/AbstractBaseProcessor.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/FulfillmentGroupOfferProcessorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/ItemOfferProcessorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/OrderOfferProcessorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/type/OfferPriceDataIdentifierType.java
  core/broadleaf-framework/src/main/resources/META-INF/persistence-framework.xml
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-entity.xml
  core/broadleaf-framework/src/main/resources/config/bc/sql/load_admin_permissions.sql
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/domain/CandidateItemOfferTest.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/service/OfferDataItemProvider.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/service/OfferServiceTest.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/service/processor/FulfillmentGroupOfferProcessorTest.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/service/processor/ItemOfferProcessorTest.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/service/processor/OrderOfferProcessorTest.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/order/domain/OrderItemTest.java
Labels: migration-required, type-enhancement

#1806 Added RTL support to radio buttons in the admin
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/blc-admin.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/entityForm.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/rtl/blc-admin.rtl.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/rtl/entityForm.rtl.css
Labels: type-enhancement
