Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-10, with the labels that each got.

#1990 Foreign key lookups on Content Items should show the entity's name, not ID
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/server/handler/StructuredContentTypeCustomPersistenceHandler.java
Labels: severity-major, type-bug

#1991 Update minification to skip files that have min in their file extension
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceMinificationServiceImpl.java
Labels: type-feature

#1767 Introduce a generic mechanism for providing custom hints to the system during query execution
  common/src/main/java/org/broadleafcommerce/common/persistence/QueryHelper.java
  common/src/main/java/org/broadleafcommerce/common/persistence/QueryHelperHints.java
  common/src/main/java/org/broadleafcommerce/common/persistence/QueryHelperImpl.java
Labels: severity-minor, type-enhancement

#1992 Fixed issue for chrome58 where WYSIWYG editor was not correctly marking up the text
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
Labels: difficulty-easy, severity-major, type-bug

#1996 Password field's label should not display the actual password value
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/fields/password.html
Labels: severity-critical, type-bug

#1999 Add missing payment type to payment request DTO
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderToPaymentRequestDTOServiceImpl.java
Labels: type-bug

#2002 Truncate timestamps when adding demo data to a Postgres database
  common/src/main/java/org/broadleafcommerce/common/util/sql/importsql/DemoPostgresSingleLineSqlCommandExtractor.java
Labels: severity-minor, type-bug

#2007 Fix template error when opening admin reset password link
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/login/resetPassword.html
Labels: target-6.0.0-GA, type-bug

#2008 Make Solr search method configurable via a property
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
Labels: type-enhancement

#2005 Return true when there is a defaultValue so that the NO VALUE SELECTED option will not show
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/BasicFieldMetadata.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/fields/data_driven_enumeration.html
Labels: severity-minor, type-bug

#2004 BroadleafCommerce/QA#3457 - Adding an opportunity to customize error …
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/RequiredIfPropertyValidator.java
Labels: severity-major, type-bug

#1989 When deleting (archiving) a product the associated skus were not getting archived
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
Labels: type-enhancement

#1982 Fix NPE When Visitng Checkout as Customer w/o a Real Cart
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderToPaymentRequestDTOServiceImpl.java
Labels: type-bug

#1945 Add support for overriding generated index names for Broadleaf Filter columns
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/copy/DirectCopyTransformMember.java
  common/src/main/java/org/broadleafcommerce/common/filter/Filter.java
  common/src/main/java/org/broadleafcommerce/common/weave/ConditionalDirectCopyTransformMemberDto.java
Labels: severity-minor, type-bug

#2010 Fixed JS error when the admin error page shows
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: severity-medium, type-bug

#2011 Remove the currency prefix from the value based on the current currency
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
Labels: severity-medium, type-bug
