Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2018-09, with the labels that each got.

#1978 Introduce Transactional boundary for this service to ensure that the pricingWorkflow's activities take effect
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/PricingServiceImpl.java
Labels: severity-medium, type-bug

#1796 Added filter for deleted/archived product to the readProductsByName query
  core/broadleaf-framework/src/main/resources/config/bc/jpa/domain/Product.orm.xml
  integration/src/test/java/org/broadleafcommerce/core/catalog/dao/ProductDaoTest.java
Labels: severity-minor, target-5.2.4-GA, target-5.3.0-GA, type-bug

#1977 Fixes the issue where filter applied to entity list-grid carries over to switch site modal
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: severity-minor, type-bug

#1794 Provide optional support for Html minification
  common/pom.xml
  common/src/main/java/org/broadleafcommerce/common/web/util/HtmlMinifyFilter.java
  pom.xml
Labels: severity-minor, type-enhancement

#1972 Add AdminPresentation fields to admin user to trigger Oracle handling of blank fields
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminUserImpl.java
Labels: severity-major, type-bug

#1947 Changed redirect path for AJAX requests.
  common/src/main/resources/common_style/templates/utility/blcRedirect.html
Labels: severity-minor, type-bug

#1981 Fixed issue where a subcollection entity name can be a null reference in the enterprise workflow process
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/AdminEntityServiceImpl.java
Labels: severity-minor, type-bug

#1980 Added a method to exclude fields from being 'redactored'
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
Labels: type-enhancement

#1986 If the object name is blank, do not append the appName
  common/src/main/java/org/broadleafcommerce/common/jmx/AnnotationJmxAttributeSource.java
Labels: severity-major, type-bug
