Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-05, with the labels that each got.

#2098 Upgrade spring security to latest release
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/BroadleafEntityValidator.java
  pom.xml
Labels: type-security

#2103 Fixed an issue where Category Relevancy Rules don't boost results
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/dao/SolrIndexDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
Labels: severity-minor, type-bug

#2101 Adding an EntityIdentifierUtil class to uses Reflection to find the Identifier (@id) field in an entity bean
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/BroadleafEntityValidator.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/EntityIdentifierUtil.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext.xml
Labels: severity-medium, type-bug

#2106 Customer ChallengeQuestion lazy fetch
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/CustomerImpl.java
Labels: severity-minor, type-bug

#2109 Fixed an issue where deleting a product does not archive the associated skus
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/ProductCustomPersistenceHandler.java
Labels: severity-minor, type-enhancement

#2110 Upgrade jQuery to latest version 3.4.1
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.datetimepicker.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.event.move.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/new-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.4.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.4.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
Labels: severity-critical, type-bug

#2112 Fixed an issue related with Product option values special charater
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicOperationsController.java
Labels: severity-minor, type-bug

#2115 Content Items are showing duplicates of all the fields (carried over …
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldGroup.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldGroupImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentFieldTemplateImpl.java
Labels: severity-medium, target-6.0.3-GA, type-bug

#2113 Potential XSS vulnerability, antisamy filter doesn't react on javascript in plain string
  common/src/main/java/org/broadleafcommerce/common/security/service/ExploitProtectionServiceImpl.java
  common/src/test/java/org/broadleafcommerce/common/security/service/ExpolitProtectionServiceTest.java
Labels: severity-minor, type-bug

#2118 Unable to sort Products by Default Category. Added a property that di…
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/extension/ParentCategorySortExtensionHandler.java
  common/src/main/resources/config/bc/common.properties
Labels: type-bug

#2117 Check the ContentType of file media uploads based on the type of Inpu…
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetServiceImpl.java
  admin/broadleaf-contentmanagement-module/src/main/resources/config/bc/cms/common.properties
Labels: target-5.2.12-GA, type-enhancement
