Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-06, with the labels that each got.

#2124 Fixed an issue where Validation error message are not showing in the ADMIN UI
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: severity-medium, type-bug

#2127 Corrected Base Products admin section's permissions
  core/broadleaf-framework/src/main/resources/config/bc/sql/load_admin_menu.sql
Labels: module-core, severity-minor, target-5.2.13-GA, target-5.3.0-GA, target-6.0.5-GA, type-bug

#2125 Allows not initial resource bundle requests to not specify mapping prefix and file list.
  common/src/main/java/org/broadleafcommerce/common/web/request/ResourcesRequest.java
Labels: type-bug

#2128 Refactored the resource resolution to resolve a theme from the request parameter
  common/src/main/java/org/broadleafcommerce/common/web/ThemeUrlEncodingFilter.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/ResourceBundleProcessor.java
Labels: severity-major, type-bug

#2122 The content targeting functionality that swaps out the theme was moved to separate filter
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeResolverFilter.java
Labels: severity-medium, type-bug
