Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-02, with the labels that each got.

#1987 The sandbox ribbon datepicker was not respecting different client and server time zones
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafSandBoxResolverImpl.java
  common/src/main/java/org/broadleafcommerce/common/web/expression/BRCVariableExpression.java
Labels: severity-minor, type-bug

#2063 Add help text message on list grid for offer codes
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/component/ListGrid.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/listGrid.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/partials/entityFormFields.html
Labels: severity-minor, type-bug

#2064 Fixed a bug in the indication of dirty fields in HTML.
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/FieldPersistenceProviderAdapter.java
Labels: target-5.2.8-GA, type-bug

#2066 The value attribute of a ProductOptionValue is now required
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionValueImpl.java
Labels: type-enhancement

#2065 Added validation that does not allow duplicates offer codes
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCodeCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/bl-admin-applicationContext.xml
  admin/broadleaf-admin-module/src/main/resources/messages/UtilityMessages.properties
Labels: type-feature

#2052 Prevent incorrect validation warning from programmatic sorts
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
Labels: severity-minor, type-bug

#2068 Fixes the issue where API cart fails due to ClassCastException
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
Labels: severity-medium, target-5.2.9-GA, type-bug

#2067 Added readOnly attribute validation because Offer Restriction Rules do not honor admin privileges
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/ruleBuilder.html
Labels: target-5.2.9-GA, type-bug

#2060 Fix issue where validations on translations where running during add replay operations
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/handler/TranslationCustomPersistenceHandler.java
Labels: severity-medium, type-bug

#2038 Removing the property "bl_merge_cart_response""
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/order/security/CartStateRequestProcessor.java
Labels: severity-minor, type-bug

#2026 Fixed admin tooltip overlay
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/tooltips.css
Labels: severity-minor, type-bug

#2025 BroadleafEntityValidator enables entity/form validation
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/BroadleafEntityValidator.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
Labels: type-enhancement

#1961 Add item attributes to orderItemRequestDTO on update
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/update/ValidateUpdateRequestActivity.java
Labels: severity-minor, type-bug

#2069 Use the currency of the order instead of the default currency in checkout
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/workflow/ValidateAndConfirmPaymentActivity.java
Labels: type-bug

#2070 Fix issue that prevented extended classes from participating in tab and field creation
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/DynamicEntityDaoImpl.java
Labels: severity-minor, type-bug
