Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-09, with the labels that each got.

#2158 Fix product options performance issue on product form
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
Labels: ready-for-code-review, type-bug

#2160 Fix performance issue on product edit screen with large number of product options
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
Labels: severity-minor, type-bug

#2159 Added SKU availability verification on checkout
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/workflow/ValidateAvailabilityActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/ContextualInventoryService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/InventoryServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/AbstractCheckAvailabilityActivity.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-workflow.xml
  core/broadleaf-framework/src/test/groovy/org/broadleafcommerce/core/spec/checkout/service/workflow/ValidateAvailabilityActivitySpec.groovy
  core/broadleaf-framework/src/test/groovy/org/broadleafcommerce/core/spec/order/service/workflow/CheckAddAvailabilityActivitySpec.groovy
  core/broadleaf-framework/src/test/groovy/org/broadleafcommerce/core/spec/order/service/workflow/CheckUpdateAvailabilityActivitySpec.groovy
  integration/src/test/java/org/broadleafcommerce/common/workflow/WorkflowTest.java
  integration/src/test/resources/bl-applicationContext-test.xml
Labels: type-bug

#2163 Upgraded Xstream from 1.3.1 to 1.4.11.1 due to published security issue (CVE-2013-7285)
  pom.xml
Labels: severity-medium, type-bug
