Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-11, with the labels that each got.

#2190 Cannot upload an image from the Product page on community edition
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/web/controller/AdminAssetUploadController.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/assetSelector.js
Labels: severity-severe, target-6.0.7-GA, type-bug

#2192 Fix issue where a customer can't add addresses when using MySQL
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerAddressDaoImpl.java
  core/broadleaf-profile/src/main/resources/config/bc/jpa/domain/CustomerAddress.orm.xml
Labels: severity-critical, type-bug

#2193 Revert Hibernate 5.3 sequence generator strategy back to the old strategy
  common/src/main/resources/config/bc/common.properties
Labels: severity-medium, type-bug

#2195 Remove old versions of jQuery files
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/jquery-2.1.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.min.js
Labels: type-bug

#2196 Add special case when translating MVEL expressions for between expressions for numbers
  admin/broadleaf-admin-module/src/test/java/org/broadleafcommerce/admin/web/rulebuilder/MVELToDataWrapperTranslatorTest.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/MVELToDataWrapperTranslator.java
Labels: severity-medium, target-6.1.0-GA, type-bug

#2197 Update the creation and resolution of the jcache.xml file to be a real file and not just in memory
  admin/broadleaf-contentmanagement-module/src/main/resources/META-INF/persistence-cms.xml
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/DefaultJCacheUtil.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/jcache/MergeJCacheManagerFactoryBean.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/JCachePersistenceUnitPostProcessor.java
  common/src/main/java/org/broadleafcommerce/common/io/AbstractRegisteringURLStreamHandler.java
  common/src/main/java/org/broadleafcommerce/url/handler/jcache/Handler.java
  common/src/main/java/org/broadleafcommerce/url/handler/jcache/MergedJCacheUrlConnection.java
  common/src/main/resources/META-INF/persistence-common.xml
  common/src/main/resources/bl-common-applicationContext-persistence.xml
Labels: type-bug

#2200 Fixes JS error on past deployments listgrid
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-medium, type-bug

#2184 Fixed an issue where Can not run Reference Site in "Create" mode if your JVM locale not exist in blc_locale
  common/src/main/java/org/broadleafcommerce/common/i18n/service/TranslationServiceImpl.java
Labels: severity-minor, type-bug

#2201 Adds missing functionality back to `entityForm-status` logic
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm-status.js
Labels: severity-critical, type-bug

#2198 Fixed an issue When go back from product screen list grid fails to scroll
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: severity-minor, type-bug

#2199 Fixed an issue When go back from product screen list grid fails to scroll
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: severity-minor, type-bug
