Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-04, with the labels that each got.

#2088 Fixed Profile Propagation Issues
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldGroupImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentFieldGroupXrefImpl.java
Labels: severity-major, type-bug

#2091 Override protobuf dependency to use latest version
  common/pom.xml
Labels: type-security

#2092 Remove weaved in AdminAuditable and Add embedded Auditable
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderItemImpl.java
Labels: severity-medium, type-bug

#2094 Put the details of the request in a TRACE log level on PaymentGatewayAbstractController
  common/src/main/java/org/broadleafcommerce/common/web/payment/controller/PaymentGatewayAbstractController.java
Labels: type-enhancement

#2093 Fixed JS error on Category reorder
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-minor, type-bug

#2097 Fixed an issue where Сontent targeter with alternate theme and with web request rule cause an NP
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafRequestProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/resource/BroadleafContextUtil.java
Labels: severity-medium, type-bug

#2096 Add support for validation errors on adding to lists
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminJavascriptMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/ui/messages_en.js
Labels: target-6.0.3-GA, type-bug

#2100 Sku Media collection ordering via Admin
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/BroadleafEntityValidator.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/mediaGrid.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/mediaListGrid.html
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/SkuMediaDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/SkuMediaDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/OrderedSkuMediaXref.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Sku.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/SkuMediaService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/SkuMediaServiceImpl.java
Labels: target-6.0.3-GA, type-enhancement
