Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-07, with the labels that each got.

#2132 Fixed an issue where re-order the displayed categories on list grid gives errors
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-medium, type-bug

#2130 Added property to allow sorting on a Product's parent Category to be disabled in the Admin due to unresolvable issues.
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/extension/ParentCategorySortExtensionHandler.java
  common/src/main/resources/config/bc/common.properties
Labels: target-5.2.13-GA, type-bug

#2133 Fixed issue when offer is applied for different locale, amount off is not converted
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/AbstractOfferValueModifierExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferValueModifierExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferValueModifierExtensionManager.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/workflow/OfferActivity.java
Labels: severity-major, type-bug

#2139 Fixed an issue where Scrolling through lookup does not load all records
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: severity-critical, type-bug

#2140 Fix Category reordering issue where the collection would refresh with unrelated categories
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/AdminSecurityServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/BroadleafEntityValidator.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeResolverFilter.java
  common/src/main/java/org/broadleafcommerce/common/web/ThemeUrlEncodingFilter.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/CustomerImpl.java
Labels: severity-major, type-bug
