Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-12, with the labels that each got.

#2203 Fixed an issue where Login page the head element has another nested head element
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/loginLayout.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/loginHead.html
Labels: severity-minor, type-bug

#2204 Fixed an issue where XSS Vulnerability in demo site
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/checkout/validator/CheckoutPaymentInfoFormValidator.java
Labels: severity-minor, type-bug

#2206 Added new runtime class transformer that allows specific cache regions to be disabled
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/cache/RemoveCacheClassTransformer.java
Labels: type-enhancement

#2207 Fixed issue when CF does not showing up on Category form
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/FieldEntity.java
Labels: severity-medium, type-bug

#2208 Fixed issue where multiple offers with minimum order subtotal requirements can get skipped
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/FulfillmentGroupOfferProcessorImpl.java
Labels: severity-minor, type-bug

#2209 Fix selectors after jquery upgrade
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: severity-minor, type-bug

#2202 Fixes issue with bundled resource references having a hardcoded ID
  common/src/main/java/org/broadleafcommerce/common/web/processor/AbstractResourceProcessor.java
Labels: severity-minor, type-bug

#2213 Support blank non-required FK lookup page fields
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/service/PageServiceUtility.java
Labels: module-cms, severity-minor, target-6.0.7-GA

#2214 Fix issue for empty date_create and date_updated fields in for order items
  common/src/main/java/org/broadleafcommerce/common/exception/OptimisticLockInvalidStateException.java
  common/src/main/java/org/broadleafcommerce/common/exception/OptimisticLockMaxRetryException.java
  common/src/main/java/org/broadleafcommerce/common/util/OptimisticLockUtils.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderItemImpl.java
Labels: severity-minor, type-bug
