Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-10, with the labels that each got.

#2167 Updated resource URL encoding process to only lookup the Theme if needed
  common/src/main/java/org/broadleafcommerce/common/file/service/StaticAssetPathServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeResolver.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeResolverFilter.java
  common/src/main/java/org/broadleafcommerce/common/web/ThemeUrlEncodingFilter.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/AbstractResourceProcessor.java
Labels: severity-major, type-bug

#2175 Register SkuProductOptionValueXref bean & Add Sku Generation logging
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/AdminCatalogServiceImpl.java
  admin/broadleaf-admin-module/src/main/resources/admin_style/js/admin/catalog/product.js
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-entity.xml
Labels: type-enhancement

#2176 Avoiding translation calls for the default locale
  common/src/main/java/org/broadleafcommerce/common/i18n/service/DynamicTranslationProvider.java
  common/src/main/java/org/broadleafcommerce/common/i18n/service/TranslationService.java
  common/src/main/java/org/broadleafcommerce/common/i18n/service/TranslationServiceImpl.java
  integration/src/test/java/org/broadleafcommerce/test/translation/sitejvm/TranslationServiceTest.java
Labels: ready-for-code-review, severity-minor, type-enhancement

#2171 Upgrade JQuery to address XSS issue
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin-init.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.datetimepicker.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.event.move.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/responsive-tables.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/new-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/dropdown.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.4.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.4.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/moment-with-locales.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
Labels: severity-medium, severity-minor, type-bug

#2179 For performance, clearing the L1 cache after each reindex loop
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexServiceImpl.java
Labels: severity-medium, type-bug

#2178 Refactor default CustomerAddressService/DAO logic to improve performance
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/account/BroadleafManageCustomerAddressesController.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerAddressDao.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerAddressDaoImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/service/CustomerAddressServiceImpl.java
  core/broadleaf-profile/src/main/resources/config/bc/jpa/domain/CustomerAddress.orm.xml
  integration/src/test/java/org/broadleafcommerce/profile/web/core/service/CustomerAddressTest.java
  integration/src/test/java/org/broadleafcommerce/test/CommonSetupBaseTest.java
Labels: severity-medium, type-bug

#2182 Fixes xform template ordering during class transformation
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/copy/DirectCopyClassTransformer.java
Labels: ready-for-code-review, severity-minor, type-bug

#2166 Fix to remove excessive calls to server when changing catalog/profile in admin
  common/src/main/resources/common_style/js/BLC.js
Labels: severity-minor, type-bug

#2173 Fixed an issue where editor is not working properly
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
Labels: type-bug

#2169 Fixed an issue where Read only table still allows reorder edits
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
Labels: type-bug

#2186 Prevent leading 0s from being removed for text-list rule-builder
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
Labels: severity-medium, type-bug

#2187 Prevent leading 0s from being removed for text-list rule-builder
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
Labels: type-bug

#2183 fix(theme): Made theme change detection null-safe
  common/src/main/java/org/broadleafcommerce/common/site/domain/ThemeDTO.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeProcessor.java
Labels: target-6.0.7-GA, type-bug

#2188 Not able to add Sku with options to cart, hibernate proxy is not deproxied correctly
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/copy/DirectCopyClassTransformer.java
  common/src/main/java/org/broadleafcommerce/common/i18n/service/DynamicTranslationProvider.java
  common/src/main/java/org/broadleafcommerce/common/i18n/service/TranslationService.java
  common/src/main/java/org/broadleafcommerce/common/i18n/service/TranslationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/util/dao/DynamicDaoHelperImpl.java
  common/src/main/resources/common_style/js/BLC.js
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/account/BroadleafManageCustomerAddressesController.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerAddressDao.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerAddressDaoImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/service/CustomerAddressServiceImpl.java
  core/broadleaf-profile/src/main/resources/config/bc/jpa/domain/CustomerAddress.orm.xml
  integration/src/test/java/org/broadleafcommerce/profile/web/core/service/CustomerAddressTest.java
  integration/src/test/java/org/broadleafcommerce/test/CommonSetupBaseTest.java
  integration/src/test/java/org/broadleafcommerce/test/translation/sitejvm/TranslationServiceTest.java
Labels: type-bug
