Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-01, with the labels that each got.

#2047 Upgrade tika-core to latest patch 1.20 for security vulnerabilities
  pom.xml
Labels: severity-minor, type-security

#1801 Fix incorrectly seeing pending changes warning
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm-status.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: severity-medium, type-bug

#2054 Added new interface method, that will returns all site parent ids.
  common/src/main/java/org/broadleafcommerce/common/file/service/BroadleafFileServiceExtensionHandler.java
Labels: severity-minor, type-bug

#2048 BroadleafCommerce/QA#3539 - Fix to OrderItemPriceDetail not syncd from OrderItem when OrderItem.isDiscountingAllowed is false
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceUtilitiesImpl.java
Labels: severity-medium, type-bug

#2058 Update sandbox ribbon and show "saved" message when changing products order in products bundle
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-minor, type-bug

#2057 Added a readOfferCodesByIds method to reduce multiple trips to the database
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferCodeDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferCodeDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
Labels: type-feature
