Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2019-08, with the labels that each got.

#2143 Fix startup error when deploying to Tomcat as a WAR
  common/src/main/java/org/broadleafcommerce/common/web/ThemeUrlEncodingFilter.java
Labels: severity-medium, type-bug

#2129 Incorrectly sending transactions to Google Analytics on "reorder" page
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafOrderConfirmationController.java
Labels: severity-minor, type-bug

#2144 Fixed an issue when Theme fields not updating when parent ThemeConfiguration is removing
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-minor, type-bug

#2148 Added a getter and setter methods for the Auditable field to OrderItem domain class
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderItem.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderItemImpl.java
Labels: severity-minor, type-bug

#2147 Fix Solr alphabetical sort doesn't consider word order
  core/broadleaf-framework/src/main/resources/config/bc/sql/demo/load_catalog_data.sql
Labels: severity-minor, type-bug

#2150 Import.sql.enabled now creates base site/admin user
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/demo/ImportSQLConfig.java
  admin/broadleaf-contentmanagement-module/src/main/resources/config/bc/sql/demo/load_content_structure.sql
  admin/broadleaf-contentmanagement-module/src/main/resources/config/bc/sql/demo/load_locale.sql
  common/src/main/java/org/broadleafcommerce/common/demo/ImportSQLConfig.java
Labels: type-bug

#2151 Fixed an issue where Error appears in validation URL's for XSS on Admin
  common/src/main/java/org/broadleafcommerce/common/security/service/ExploitProtectionServiceImpl.java
Labels: type-bug

#2155 Fixed bug where category sequence was calculated incorrectly
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: severity-minor, target-5.2.14-GA, type-bug

#2153 fix exception when reverting new product
  admin/broadleaf-open-admin-platform/src/main/resources/applicationContext-servlet-open-admin.xml
Labels: target-5.2.14-GA, type-bug

#2149 Fixed issue when field is not highlighting for adorned collection metadata
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/ParentRecordStructure.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/visitor/PersistencePerspectiveItemVisitor.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/visitor/PersistencePerspectiveItemVisitorAdapter.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/AdminEntityService.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/AdminEntityServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/presentation/client/PersistencePerspectiveItemType.java
Labels: target-5.2.14-GA

#2152 fix read only table
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/listGrid.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
Labels: target-5.2.4-GA, type-bug

#2154 add missed class
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-entity.xml
Labels: target-5.2.14-GA, type-bug
