Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-12, with the labels that each got.

#2433 Make XFormsParams protected
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/SkipDefaultConstructorCheck.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/copy/DirectCopyClassTransformer.java
Labels: type-enhancement

#2447 QA-4274 Fixed security vulnerabilities in the JQuery and JUnit libraries via updating
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery.dataTables.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery.dataTables.min.js
  pom.xml
Labels: severity-critical, type-security

#2440 Add support of uniqueConstraints to DirectCopyClassTransformer
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldGroupImpl.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/copy/DirectCopyClassTransformer.java
Labels: type-enhancement

#2448 Remove deprecated admin presentation overrides
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/AdornedTargetCollectionFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BasicFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/CollectionFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/MapFieldMetadataProvider.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationAdornedTargetCollectionOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationCollectionOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationDataDrivenEnumerationOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationMapOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationOverrides.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationToOneLookupOverride.java
Labels: migration-required, type-enhancement

#2446 Fixed an issue where Editing other fields of the product is changing description of product
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
Labels: severity-major, type-bug

#2450 Fix for cascades for product, so when sku is deleted it is not cascaded to product
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
Labels: type-bug

#2451 Updated libraries and removed old Jquery files
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/jquery-2.1.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/jquery-3.5.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/jquery-3.5.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-1.11.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.min.js
  common/src/main/resources/common_style/js/lib/jquery-1.9.1.js
  common/src/main/resources/common_style/js/lib/jquery-3.5.1.js
  common/src/main/resources/common_style/js/lib/jquery-3.5.1.min.js
  pom.xml
Labels: type-security

#2452 Remove criteria builder entity casts
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/SkipDefaultConstructorCheck.java
  common/src/main/java/org/broadleafcommerce/common/sandbox/dao/SandBoxDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductOptionDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/dao/SearchFacetDaoImpl.java
Labels: type-enhancement

#2457 QA-4276 Product option attribute name prevention
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminProductController.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: type-enhancement

#2456 Replace const with var on js files to avoid minification issues
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-filter.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: severity-minor, type-bug

#2453 Fixed an issue where user is not able to add/edit scheduled jobs in the admin
  common/src/main/java/org/broadleafcommerce/common/dao/GenericEntityDaoImpl.java
Labels: severity-major, type-bug

#2459 ESAPI update to 2.2.2.0
  common/src/main/resources/esapi/ESAPI.properties
  pom.xml
Labels: type-enhancement

#2461 Fix ProductBundleImpl stackoverflow when calling equals or hashcode
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuBundleItemImpl.java
Labels: target-6.1.5-GA, type-bug

#2463 Adding logic to FormBuilder to allow Currencies to be used in RuleBuilder dropdowns
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: severity-minor, type-bug

#2449 Fixed an issue where Error when filtering role permissions tab
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: severity-major, type-bug

#2384 Fixed WYSIWYG editor to allow adding columns and rows to an HTML table
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/redactor/table.js
Labels: severity-minor, type-bug

#2454 Fixed an issue where viewing audit details the UI table can overflow and become unresponsive
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/blc-admin.css
Labels: severity-major, type-bug
