Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-05, with the labels that each got.

#2295 Fixed an issue where Inventory check doesn't work properly for products with product options
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/workflow/ValidateAvailabilityActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/CheckAddAvailabilityActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/CheckUpdateAvailabilityActivity.java
Labels: severity-minor, type-bug

#2310 Remove import SQL files that modify the sequence generator
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/demo/ImportSQLConfig.java
  admin/broadleaf-contentmanagement-module/src/main/resources/config/bc/sql/demo/load_cms_table_sequences.sql
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/demo/ImportSQLConfig.java
  core/broadleaf-framework/src/main/resources/config/bc/sql/demo/load_framework_table_sequences.sql
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/demo/ImportSQLConfig.java
  core/broadleaf-profile/src/main/resources/config/bc/sql/demo/load_profile_table_sequences.sql
Labels: target-6.1.1-GA, type-bug

#2317 Fix add translationson the primary image
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/assetSelector.js
Labels: severity-minor, type-bug

#2326 checkout of Gift card without options
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
Labels: type-bug

#2321 Fix ajax looping loading issue
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: severity-minor, target-6.0.9-GA, type-bug

#2313 ContentItem update validation issue
  admin/broadleaf-contentmanagement-module/src/main/resources/config/bc/sql/demo/load_content_structure.sql
Labels: severity-minor, type-bug

#2328 Fix cache invalidation for linked collections in Offers
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/RuleFieldPersistenceProvider.java
Labels: severity-minor, target-5.2.15-GA, type-bug
