Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-07, with the labels that each got.

#2355 Fix issue where a new customer segment could not be added from the offer page
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
Labels: severity-minor, type-bug

#2357 Upgrade lib quartz-scheduler
  pom.xml
Labels: type-security

#2361 replace script from onclick to separate scrip file
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/header.html
Labels: type-bug

#2365 Tiered offer show dependent field fix
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
Labels: type-bug

#2362 Remove usage deprecated methods
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/AdminCatalogServiceImpl.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminProductController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminPermissionImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/handler/AdminUserCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/filter/BroadleafAdminRequestProcessor.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/account/AbstractCustomerAddressController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/account/BroadleafManageWishlistController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/cart/BroadleafCartController.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CategoryImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/call/AddToCartItems.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/fulfillment/provider/BandedFulfillmentPricingProvider.java
Labels: severity-minor, type-bug

#2363 Improve jcache support so that other cache providers other than ehcache can easily be used
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/config/CmsCacheConfiguration.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/config/OpenAdminCacheConfig.java
  common/src/main/java/org/broadleafcommerce/common/config/CommonCacheConfiguration.java
  common/src/main/java/org/broadleafcommerce/common/config/dao/SystemPropertiesDaoImpl.java
  common/src/main/java/org/broadleafcommerce/common/config/domain/NullSystemProperty.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ConditionalOnEhCacheMissing.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/DefaultJCacheConfigurationBuilder.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/DefaultJCacheUriProvider.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/DefaultJCacheUtil.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/JCacheConfigurationBuilder.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/JCacheRegionConfiguration.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/OnEhCacheMissingCondition.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/ConditionalOnEhCache.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/DefaultEhCacheConfigurationBuilder.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/DefaultEhCacheUriProvider.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/DefaultEhCacheUtil.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/OnEhCacheCondition.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/jcache/JCacheUriProvider.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/jcache/MergeJCacheManagerFactoryBean.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/JCachePersistenceUnitPostProcessor.java
  common/src/main/resources/bl-common-applicationContext-persistence.xml
Labels: type-enhancement

#2366 Fixed MVEL internal quotes escaping
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/DataDTOToMVELTranslator.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/ruleBuilder.html
Labels: severity-minor, type-bug

#2368 Fix build fail
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/account/BroadleafManageWishlistController.java
Labels: severity-minor, type-bug

#2370 Enhance start date validator to check the given entity
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/AfterStartDateValidator.java
Labels: type-enhancement

#2359 MVEL expression Npe fix when reindex sales that has rules for customer
  admin/broadleaf-admin-module/src/test/java/org/broadleafcommerce/admin/web/rulebuilder/DataDTOToMVELTranslatorTest.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/DataDTOToMVELTranslator.java
Labels: type-bug

#2356 Cannot add additional content data
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldGroupImpl.java
Labels: severity-minor, target-6.1.2-GA, type-bug
