Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-09, with the labels that each got.

#2383 Remove Offer Code with API
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/AbstractOfferServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceExtensionManager.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
Labels: severity-minor, type-bug

#2398 Add back support of allowNoValueEnumOption
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/BasicFieldMetadata.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BasicFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/selectize.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/fields/broadleaf_enumeration.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/fields/data_driven_enumeration.html
Labels: type-enhancement

#2401 Fix sorting with name filter
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminAbstractController.java
Labels: severity-minor, type-bug

#2391 Expired offer code refactoring
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafCheckoutController.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferCodeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/workflow/OfferActivity.java
Labels: type-bug

#2399 Fix sorting with name filter
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminAbstractController.java
Labels: severity-minor, type-bug

#2403 Fixes an issue where the Product list from the admin Category page is filtering out Product Bundles
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminProductController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminAbstractController.java
Labels: severity-major, type-bug

#2404 Adding the ability to support dashes in the system property names created/managed in the admin
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/persistence/validation/SystemPropertyAttributeNameValidator.java
Labels: type-enhancement

#2405 Use locale specific number formats to check numbers
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/override/FieldMetadataOverride.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: severity-major, type-bug

#2400 Offer code max use fix
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
Labels: severity-minor, type-bug

#2402 Fix html tag
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: severity-minor, type-bug

#2406 Set solr optimize default false
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
Labels: severity-minor, type-bug

#2412 Fix radio buttons are not initialized
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
Labels: severity-minor, type-bug

#2411 Use PaymentType.isCreditCardType() where appropriate
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/checkout/service/CheckoutFormServiceImpl.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafBillingInfoController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafPaymentInfoController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafShippingInfoController.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/expression/checkout/PaymentMethodVariableExpression.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/order/service/CartStateServiceImpl.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/OnePageCheckoutProcessor.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/strategy/OrderPaymentConfirmationStrategyImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/SecureOrderPaymentServiceImpl.java
Labels: type-enhancement

#2413 NPE fix for FormBuilderService when ContentTargeter is created
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: severity-minor, type-bug

#2380 Adding EntityName for translations so information is available on the My Changes screen
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/handler/TranslationCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/filter/BroadleafAdminRequestFilter.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/extension/TranslationsFormBuilderExtensionHandler.java
Labels: severity-minor, type-bug

#2414 Offer currency sign
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
Labels: severity-minor, type-bug
