Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-03, with the labels that each got.

#2244 Verify that none of the selected product options is null when adding/editing SKU
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/messages/MerchandisingMessages.properties
Labels: type-bug

#2247 fix fields disabled once Approve
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: target-6.0.7-GA, type-bug

#2270 Excluding archived payment transactions from query result
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/domain/OrderPaymentImpl.java
Labels: severity-severe, type-bug

#2269 Improve getting page size in the SeoDefaultPropertyServiceImpl
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/seo/SeoDefaultPropertyServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/CategoryDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/CategoryDaoImpl.java
  core/broadleaf-framework/src/main/resources/config/bc/jpa/domain/Category.orm.xml
Labels: type-bug

#2282 Upgrade owasp.esapi version
  common/src/main/resources/esapi/ESAPI.properties
  pom.xml
Labels: target-6.0.9-GA, type-enhancement

#2285 Fixed issue where IndexFieldTypes and SearchFacetRanges were being returned in collections after they were archived
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/IndexFieldImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchFacetImpl.java
Labels: severity-minor, target-6.0.9-GA, target-6.1.1-GA, type-bug

#2286 Don't delete rule if this prop is found in another changeset that will override changes
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/RuleFieldPersistenceProvider.java
Labels: severity-minor, type-bug

#2249 Add a new request mapping for readonly collection with tabs
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
Labels: target-5.2.15-GA, type-enhancement

#2165 No error message when add transaltion for locale with existing translation
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/translations.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
Labels: severity-minor, type-bug

#2251 Fixed issue where translations could not be added to fields when the entity was part of a MappedCollection
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
Labels: severity-minor, type-bug

#2267 Fix additional content targeting action creation issue
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/DynamicEntityDao.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/DynamicEntityDaoImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/RecordHelper.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
Labels: severity-medium, type-bug

#2248 Ability to remove bundle
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceBundlingService.java
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceBundlingServiceImpl.java
Labels: type-feature

#2289 Fixed issue with order "between date" filter when it does not correctly encode a pipe delimiter in the URL
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin-history.js
  common/src/main/resources/common_style/js/BLC.js
Labels: type-bug
