Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-10, with the labels that each got.

#2407 In case of reset password link, do logic to identify profile
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/filter/BroadleafAdminRequestProcessor.java
Labels: type-bug

#2409 Fix warm messages
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldGroupImpl.java
Labels: severity-minor, type-bug

#2408 Fix reserved word rank for MySQL 8.0
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/social/domain/UserConnectionImpl.java
Labels: severity-minor, type-bug

#2423 Added the ability to override the promotion calculation logic to allow an item percent off promotion to use more precise discounting
  common/src/main/java/org/broadleafcommerce/common/money/Money.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OrderItemPriceDetailAdjustmentImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/AbstractPromotionRounding.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableFulfillmentGroupAdjustmentImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableItemFactoryImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableOfferUtilityImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotableOrderItemPriceDetailImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/discount/domain/PromotionRounding.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderItemPriceDetailImpl.java
Labels: type-enhancement

#2426 Javascript errors in the offer
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/query-builder.js
Labels: severity-minor, type-bug

#2430 Do not allow negative discount adjustments when evaluating offers
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceUtilitiesImpl.java
Labels: severity-minor, type-bug
