Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-04, with the labels that each got.

#2138 Simplified, alternate strategy for sandbox transition operations
  .gitignore
  Jenkinsfile
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/extension/AdminProductTranslationExtensionHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/AdornedTargetListPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/statement/Expression.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/statement/PhraseTranslator.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-filter.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/translations.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
  common/.gitignore
  common/src/main/java/org/broadleafcommerce/common/config/dao/SystemPropertiesDaoImpl.java
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopyContext.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/AbstractEntityInformationServiceExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationService.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationServiceExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationServiceExtensionManager.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/sandbox/service/SandBoxService.java
  common/src/main/java/org/broadleafcommerce/common/sandbox/service/SandBoxServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/util/StreamingTransactionCapableUtil.java
  common/src/main/java/org/broadleafcommerce/common/util/UpdateExecutor.java
  common/src/main/java/org/broadleafcommerce/common/web/filter/TranslationFilter.java
  common/src/main/resources/common_style/js/BLC.js
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/service/i18nUpdateCartServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/I18nSolrSearchServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/I18nSolrIndexServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/indexer/CatalogSolrIndexUpdateCommandHandlerImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/indexer/CatalogSolrIndexUpdateService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/indexer/CatalogSolrIndexUpdateServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/indexer/DefaultSolrIndexQueueProvider.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext.xml
Labels: severity-major, type-enhancement

#2288 fix usage of Content Security Policies in admin
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin-js-check.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/loginLayout.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/loginHead.html
Labels: type-enhancement

#2172 Simplified, alternate strategy for sandbox transition operations
  .gitignore
  Jenkinsfile
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/AdornedTargetListPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/statement/Expression.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/statement/PhraseTranslator.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/translations.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
  common/.gitignore
  common/src/main/java/org/broadleafcommerce/common/config/dao/SystemPropertiesDaoImpl.java
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopyContext.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/AbstractEntityInformationServiceExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationService.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationServiceExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationServiceExtensionManager.java
  common/src/main/java/org/broadleafcommerce/common/entity/service/EntityInformationServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/sandbox/service/SandBoxService.java
  common/src/main/java/org/broadleafcommerce/common/sandbox/service/SandBoxServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/util/StreamingTransactionCapableUtil.java
  common/src/main/java/org/broadleafcommerce/common/util/UpdateExecutor.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/AbstractResourceProcessor.java
  common/src/main/resources/common_style/js/BLC.js
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerAddressDaoImpl.java
  pom.xml
Labels: severity-medium, type-enhancement

#2271 Additional lazy fetch tuning
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderItemImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/AddressImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/domain/CustomerImpl.java
Labels: type-enhancement

#2294 Added new field to ListGrid for storing css classes
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/component/ListGrid.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/mediaListGrid.html
Labels: severity-minor, type-bug

#2297 Blank Personal Message rows were being created on order submit
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafShippingInfoController.java
Labels: severity-minor, type-bug

#2299 Prevents creating static asset, if file size does not pass max upload size validation
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetServiceImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetStorageService.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetStorageServiceImpl.java
Labels: severity-minor, type-bug

#2298 Add support translation for map collections
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/domain/StaticAssetImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
  common/src/main/java/org/broadleafcommerce/common/media/domain/MediaImpl.java
Labels: severity-minor, type-bug

#2304 Extending payment type with apple and google pay
  common/src/main/java/org/broadleafcommerce/common/payment/PaymentType.java
Labels: severity-major, type-bug

#2306 Add translation for media
  common/src/main/java/org/broadleafcommerce/common/i18n/domain/TranslatedEntity.java
  common/src/main/java/org/broadleafcommerce/common/media/domain/MediaImpl.java
  core/broadleaf-framework/src/main/resources/config/bc/sql/load_admin_permissions.sql
Labels: target-5.2.15-GA, type-enhancement

#2301 fixes blocked threads on mvehelper calls
  admin/broadleaf-admin-functional-tests/pom.xml
  admin/broadleaf-admin-module/pom.xml
  admin/broadleaf-contentmanagement-module/pom.xml
  admin/broadleaf-open-admin-platform/pom.xml
  admin/pom.xml
  common/pom.xml
  common/src/main/java/org/broadleafcommerce/common/rule/MvelHelper.java
  common/src/main/java/org/broadleafcommerce/common/rule/RuleCountDownLatch.java
  common/src/main/java/org/broadleafcommerce/common/util/EfficientLRUMap.java
  core/broadleaf-framework-web/pom.xml
  core/broadleaf-framework/pom.xml
  core/broadleaf-profile-web/pom.xml
  core/broadleaf-profile/pom.xml
  core/pom.xml
  integration/pom.xml
  pom.xml
Labels: ready-for-code-review, severity-major, type-bug

#2307 Add translations to search
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: type-feature
