Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-11, with the labels that each got.

#2432 Fixed an issue where Admin returns blank error page on error
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminBasicErrorController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/config/AdminWebMvcConfiguration.java
Labels: type-bug

#2435 Fix product option error message
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/ProductOptionValidationServiceImpl.java
Labels: type-bug

#2436 Fixed an issue where Duplicate Catalogs get created when rapidly clicking save button
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: severity-minor, type-bug

#2427 Fix layout for list grid actions toolbar when too many actions
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/listGrid.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/rtl/listGrid.rtl.css
Labels: type-enhancement

#2438 Populated entity type and field name for edit on admin translations controller.
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminTranslationController.java
Labels: ready-for-code-review, severity-major, type-bug

#2434 Update info on data driven enums on each metadata request, so in case of different sites data for enums should be for that site
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/DynamicEntityDaoImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BasicFieldMetadataProvider.java
Labels: severity-minor, type-bug

#2443 Qa 4257 catalog pagination in modal fix
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: type-bug

#2309 Confirmable Remove List Grid Action
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/component/DefaultListGridActions.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/component/ListGridAction.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGridToolbar.html
Labels: target-5.2.15-GA, type-feature

#2439 Fixed an issue where Various Sql errors during the 6.1 startup in create mode
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentFieldXrefImpl.java
Labels: severity-major, type-bug

#2442 Move sorting out from the getter
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/call/OrderItemRequestDTO.java
Labels: severity-minor, type-bug

#2441 Fixed an issue where Product Add-on incorrectly shows "Included"
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/call/ConfigurableOrderItemRequest.java
Labels: severity-minor, type-bug

#2445 Fix Totalitarian offer calculations
  common/src/main/java/org/broadleafcommerce/common/service/GenericEntityServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceUtilitiesImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/FulfillmentGroupOfferProcessorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/OrderOfferProcessorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/workflow/CountTotalOffersActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/workflow/DetermineOfferChangeActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/workflow/OfferActivity.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-workflow.xml
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/service/processor/FulfillmentGroupOfferProcessorTest.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/offer/service/processor/ItemOfferProcessorTest.java
Labels: severity-minor, type-bug

#2424 fix total fulfillment price
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/fulfillment/provider/BandedFulfillmentPricingProvider.java
Labels: severity-minor, type-bug
