Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-06, with the labels that each got.

#2330 Introduce simple dropdown in admin header to select the time zone that is being shown to the user
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/persistence/module/provider/TypedEntityFieldPersistenceProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/BasicFieldPersistenceProvider.java
  admin/broadleaf-open-admin-platform/src/main/resources/config/bc/admin/common.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/blc-admin.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/header.html
  common/src/main/java/org/broadleafcommerce/common/util/BLCDateUtils.java
Labels: severity-minor, type-bug

#2332 NPE for save 0 prices in product
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
Labels: severity-minor, target-5.2.15-GA, type-bug

#2331 Offer rules should allow between rules
  admin/broadleaf-admin-module/src/test/java/org/broadleafcommerce/admin/web/rulebuilder/MVELToDataWrapperTranslatorTest.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/MVELToDataWrapperTranslator.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/dto/DataDTO.java
Labels: ready-for-code-review, type-bug

#2327 Clear Offer qualifiers when switching offer type
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/extension/AbstractOfferCustomServiceExtensionHandler.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/extension/OfferCustomServiceExtensionHandler.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/extension/OfferCustomServiceExtensionManager.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/AbstractOfferServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceExtensionManager.java
Labels: severity-minor, target-5.2.15-GA, type-bug

#2325 Fix minifying javascript
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/rtl/spectrum.rtl.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/spectrum.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin-history.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/assetSelector.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/sessionTimer.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/modernizr.foundation.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.datetimepicker.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.mCustomScrollbar.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/modernizr-2.8.2.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/modernizr-3.6.0.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/spectrum.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/new-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.4.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.4.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.5.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-3.5.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery.fluidbox.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery.fluidbox.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/modernizr-2.8.2.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/modernizr-3.6.0.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
Labels: target-5.2.15-GA, type-bug

#2320 Fix warning message in console
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/rtl/spectrum.rtl.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/spectrum.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/spectrum.js
Labels: severity-minor, target-6.0.9-GA, type-bug

#2305 Fix queries cache set current date resolution
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/CategoryDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/SkuDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/config/FrameworkConfig.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/redirect/dao/SearchRedirectDaoImpl.java
Labels: severity-minor, target-6.0.9-GA, type-bug

#2156 Override missed equals hashcode serialVersionUID
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/url/domain/URLHandlerImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/BatchDynamicResultSet.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/BatchPersistencePackage.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/SectionCrumb.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/dto/DataDTO.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/dto/DataWrapper.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/dto/ExpressionDTO.java
  common/src/main/java/org/broadleafcommerce/common/config/domain/SystemPropertyImpl.java
  common/src/main/java/org/broadleafcommerce/common/extension/StandardCacheItem.java
  common/src/main/java/org/broadleafcommerce/common/persistence/ArchiveStatus.java
  common/src/main/java/org/broadleafcommerce/common/persistence/PreviewStatus.java
  common/src/main/java/org/broadleafcommerce/common/weave/ConditionalDirectCopyTransformMemberDto.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CategorySiteMapGeneratorConfigurationImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductBundleImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionXrefImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuBundleItemImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuFeeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/FieldImpl.java
  integration/pom.xml
  integration/src/test/java/org/broadleafcommerce/arch/EqualsHashCodeMethodsTest.java
Labels: target-5.2.14-GA, type-bug

#2226 Added ability to undo a local site change for translations
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminTranslationController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/TranslationFormBuilderServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/modal.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/translations.js
Labels: type-enhancement

#2335 Remove references to older jQuery versions which were not used
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/.sorting
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/jquery-2.1.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-1.11.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.min.js
  common/src/main/resources/common_style/js/lib/jquery-1.9.1.js
Labels: severity-minor, type-bug, type-security

#2342 Libs upgrade
  pom.xml
Labels: severity-minor, target-6.1.2-GA, type-bug

#2340 Fix security vulnerability, upgrade Common BeanUtils
  pom.xml
Labels: severity-minor, target-4.0.27-GA, type-bug

#2339 Fix security vulnerability, upgrade Common BeanUtils
  pom.xml
Labels: severity-minor

#2338 Fix security vulnerability, upgrade Common BeanUtils
  pom.xml
Labels: type-security

#2341 Fix security vulnerability, upgrade Common BeanUtils
  pom.xml
Labels: type-security

#2336 Fix security vulnerability, upgrade Common BeanUtils
  pom.xml
Labels: type-security

#2337 Fix security vulnerability, upgrade Common BeanUtils
  pom.xml
Labels: severity-minor, target-6.1.2-GA, type-bug

#2347 Upgrade lib
  pom.xml
Labels: severity-critical, type-security

#2349 Update spring security
  pom.xml
Labels: type-security

#2333 Fix issue where demo SQL import statements that had escaped characters and newlines didn't import correctly
  common/src/main/java/org/broadleafcommerce/common/util/sql/importsql/DemoPostgresSingleLineSqlCommandExtractor.java
Labels: severity-minor, target-6.1.2-GA, type-bug

#2351 Fix register using passwords with special characters
  core/broadleaf-framework/src/main/resources/config/bc/fw/common.properties
Labels: severity-minor, target-6.1.2-GA, type-bug

#2329 Fix to admin Schedule Jobs UI when fetching long parameters
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
Labels: severity-minor, type-bug

#2346 Introduce dummy cache that will not cache anything
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/NoOpCache.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/NoOpCacheManager.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/jcache/MergeJCacheManagerFactoryBean.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/JCachePersistenceUnitPostProcessor.java
Labels: type-feature

#2291 Remove unused mergeCartResponseKey
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/order/security/CartStateRequestProcessor.java
Labels: type-enhancement

#2292 Don't save mergeCartResponse to session
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/order/security/CartStateRequestProcessor.java
Labels: severity-minor, type-bug

#2350 Remove internal SessionFixationProtectionFilter
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/site/security/SessionFixationProtectionCookie.java
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/site/security/SessionFixationProtectionFilter.java
Labels: severity-minor, target-6.1.2-GA, type-enhancement

#2354 Clean up old lib and upgrade to latest version
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/.sorting
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/jquery-2.1.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-1.11.1.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery-2.1.1.min.js
  common/src/main/resources/common_style/js/lib/jquery-1.9.1.js
Labels: target-6.0.9-GA, type-enhancement
