Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-08, with the labels that each got.

#2376 Redirect to the desired view doesn't work for extended exception
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/handler/AdminMappingExceptionResolver.java
Labels: severity-minor, type-bug

#2374 Use better message for exceeding max use of offer code
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafCheckoutController.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/workflow/VerifyCustomerMaxOfferUsesActivity.java
Labels: type-bug

#2367 Fix getting correct catalog
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/dao/MultipleCatalogExtensionManager.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/filter/BroadleafAdminRequestProcessor.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/handler/MultipleCatalogExtensionHandler.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
  common/src/main/resources/common_style/js/BLC.js
Labels: severity-minor, type-bug

#2382 site change locale fix
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  common/src/main/resources/common_style/js/BLC.js
Labels: type-bug

#2378 Track that offer code was removed from the cart because of expiration and notify user
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafCheckoutController.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferCodeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
Labels: type-enhancement

#2387 Adding ability to mark a payment type as "Credit Card Type" for transaction confirmation handling
  common/src/main/java/org/broadleafcommerce/common/payment/PaymentType.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/strategy/OrderPaymentConfirmationStrategyImpl.java
Labels: severity-minor, type-bug

#2389 Changes to support validation on CMS fields
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/server/handler/PageTemplateCustomPersistenceHandler.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/server/handler/StructuredContentTypeCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorService.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/entityForm.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: type-enhancement

#2390 With cache off actuator mbean for cache is failing on startup
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/NoOpCache.java
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/NoOpCacheManager.java
Labels: type-bug

#2379 MVEL to SOLR translation enhancements
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchCriteria.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/MvelToSearchCriteriaConversionServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/search/service/solr/MvelToSearchCriteriaConversionServiceImplTest.java
Labels: type-enhancement

#2394 New Credit Card types
  common/src/main/java/org/broadleafcommerce/common/payment/PaymentType.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/strategy/OrderPaymentConfirmationStrategyImpl.java
Labels: type-enhancement

#2397 Fix scroll after the refactoring to be compatible with ES5/6
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.mCustomScrollbar.js
  common/src/main/java/org/broadleafcommerce/common/resource/service/ResourceMinificationServiceImpl.java
Labels: severity-critical, type-bug
