Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2020-01, with the labels that each got.

#2215 Add a property to disable solr optimize call
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexServiceImpl.java
Labels: severity-minor, type-enhancement

#2218 Adding a default index on PROPERTY_NAME to BLC_SYSTEM_PROPERTY
  common/src/main/java/org/broadleafcommerce/common/config/domain/SystemPropertyImpl.java
Labels: type-enhancement

#2170 NameResponse inner class without getters and Setters #3767
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderToPaymentRequestDTOServiceImpl.java
Labels: affects-6.0.x-GA

#2224 For Ratings Summary, bypass readRating query if ratingSummary ID is not available
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/rating/service/RatingServiceImpl.java
Labels: type-enhancement

#2234 Added getter to skip dynamic adjustments on ProductOptionValue
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionValue.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionValueImpl.java
Labels: affects-6.0.x-GA, ready-for-code-review, severity-medium, target-6.0.7-GA, type-bug

#2189 fix error veiw price list remove
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminAbstractController.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: target-5.2.15-GA, type-bug

#2239 Update versions to recommended patches.
  pom.xml
Labels: type-security

#2185 Fix NPE in Theme resolution when running community
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafThemeProcessor.java
Labels: severity-medium, type-bug

#2240 Fixes CustomField INTEGER type validation
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/BasicFieldTypeValidator.java
Labels: severity-minor, type-bug

#2241 Fixed an issue where Could not change catalog on Global Admin
  common/src/main/resources/common_style/js/BLC.js
Labels: severity-medium, type-bug
