Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2021-12, with the labels that each got.

#2604 Added Dependency exclusions to remove dependency issues found by enforcer plugin.
  common/pom.xml
  core/broadleaf-framework-web/pom.xml
  pom.xml
Labels: type-enhancement, severity-minor

#2605 Replace hash in the URL during duplication of product with underscore.
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/ProductDuplicateModifier.java
Labels: type-bug, severity-minor

#2606 Moved filtering by locate to sql Query in readNamedOrderFor
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
  core/broadleaf-framework/src/main/resources/config/bc/jpa/domain/Order.orm.xml
Labels: type-enhancement

#2610 Added addCustomCriteria to AdminProductController
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminProductController.java
Labels: type-bug, severity-minor

#2607 Fixed anonymous customer's ID checking
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/core/CustomerStateRefresher.java
Labels: type-bug

#2611 SessionOrderLockManager marked as deprecated
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/order/SessionOrderLockManager.java
Labels: type-enhancement

#2612 Upgrade log4j to 2.15.0 for 5.1
  pom.xml
Labels: severity-critical, type-security

#2613 Upgraded log4j and excluded from xmlbeans for 5.2
  pom.xml
Labels: type-security

#2615 Removed redundant concurrency protection
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/CheckoutServiceImpl.java
Labels: type-enhancement

#2617 Changed definition of validationStringExists
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/ProductOptionValidationServiceImpl.java
Labels: type-bug, severity-minor

#2609 Add more information in duplication validation error message
  admin/broadleaf-admin-module/src/main/resources/messages/UtilityMessages.properties
Labels: type-enhancement

#2616 Fixed an issue where Listgrid column titles and data are not aligning
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: type-bug

#2618 Added synchronized for createNewCartForCustomer
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
Labels: type-bug, severity-minor
