Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2021-03, with the labels that each got.

#2468 Improve logic on building invalid product option error message
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/ProductOptionValidationServiceImpl.java
Labels: ready-for-code-review, severity-minor, target-6.1.5-GA, type-enhancement

#2469 Update XSS Filter and Wrapper strip XSS logic
  common/src/main/resources/esapi/validation.properties
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/security/XssFilter.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/security/XssRequestWrapper.java
Labels: ready-for-code-review, severity-minor, target-6.1.5-GA, type-enhancement, type-security

#2464 Do not assign id to anonymous customers
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/controller/RegisterCustomerController.java
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/core/security/CustomerStateRequestProcessor.java
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/core/service/register/RegistrationServiceImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/service/CustomerService.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/service/CustomerServiceImpl.java
  integration/src/test/java/org/broadleafcommerce/core/offer/service/OfferServiceTest.java
  integration/src/test/java/org/broadleafcommerce/test/CommonSetupBaseTest.java
Labels: ready-for-code-review, type-enhancement

#2494 Do not use a message lookup when checking for media grid row actions
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/mediaGrid.html
Labels: ready-for-code-review, severity-minor, type-bug

#2495 Add Days count and Limit to the historical purge parameters
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/type/PurgeOrderHistoryVariableNames.java
Labels: type-enhancement

#2496 Fixes permissions for SkuAttribute
  core/broadleaf-framework/src/main/resources/config/bc/sql/load_admin_permissions.sql
Labels: severity-minor, type-bug

#2497 Fixed 'Unlink' button for the Redactor link
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
Labels: severity-minor, type-bug

#2360 Add a scheduled job to purge historical orders
  common/pom.xml
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/AbstractResourcePurgeExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/DeleteStatementGenerator.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/DeleteStatementGeneratorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeExtensionManager.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/type/PurgeOrderHistoryVariableNames.java
  core/broadleaf-framework/src/main/resources/config/bc/fw/common.properties
  pom.xml
Labels: type-enhancement
