Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2021-09, with the labels that each got.

#2559 Removed an unused static reference to TranslationImpl in TranslationServiceImpl. This reference can cause a startup issue with class transformations.
  common/src/main/java/org/broadleafcommerce/common/i18n/service/TranslationServiceImpl.java
Labels: type-bug, severity-minor

#2557 jquery-ui upgrade to 1.12.1
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/head.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/loginHead.html
  common/src/main/resources/common_style/css/admin/jquery-ui-1.12.1.custom.css
  common/src/main/resources/common_style/css/jquery-ui-1.12.1.custom.css
  common/src/main/resources/common_style/js/lib/plugins/jquery-ui-1.10.2.custom.js
  common/src/main/resources/common_style/js/lib/plugins/jquery-ui-1.12.1.custom.js
Labels: type-enhancement

#2573 Extract validation error logging for the PersistenceManagerImpl
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
Labels: type-bug

#2569 Added validation for setting cross-sale and up-sale Product
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/ProductCustomPersistenceHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
Labels: type-bug

#2568 Take into account parent order
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferAuditDaoImpl.java
Labels: type-enhancement

#2575 Check property on null while building Collection List Grid
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: type-bug, severity-major

#2576 Update jquery.dataTables.js from 1.10.22 to 1.11.2
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery.dataTables-1.11.2.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery.dataTables-1.11.2.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/jquery.dataTables.min.js
Labels: type-bug, severity-critical

#2574 Fixed Incorrect behavior when using exploitProtection.xssEnabled
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/entityTitle.html
Labels: type-bug, severity-major

#2572 Added the ability for DirectCopyClassTransformer to replace a class-level @Cache annotation
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/copy/DirectCopyClassTransformer.java
Labels: type-enhancement
