Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2021-01, with the labels that each got.

#2455 Upgrade Hibernate from 4.3.15 to 4.3.20 for security reasons
  pom.xml
Labels: type-security

#2465 Deproxy nested fields when reading field values
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/FieldManager.java
Labels: ready-for-code-review, severity-minor, type-bug

#2458 Add extension handler to filter-out add-ons for site map
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/ProductSiteMapGenerator.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/AbstractSiteMapExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/SiteMapExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/SiteMapExtensionManager.java
  core/broadleaf-framework/src/test/java/org/broadleafcommerce/core/catalog/service/ProductSiteMapGeneratorTest.java
Labels: severity-minor, type-bug

#2466 QA-4319 Fixed "category removing" trigger
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-minor, type-bug

#2467 Decode validation string when xss protection is enabled
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/ProductOptionValidationServiceImpl.java
Labels: ready-for-code-review, severity-minor, target-6.1.5-GA, type-bug

#2471 Fix errors while adding/changing Content Targeters
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: severity-major, type-bug

#2475 Editing Scheduled Job parameters fix
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
Labels: type-bug

#2470 Fix performance issues due to processing time of hashCode() on ProductOptionImpl
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionImpl.java
Labels: severity-minor, type-bug

#2479 Redactor Edit Link checkbox change event fix
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
Labels: type-bug

#2484 Fixed issue where creation of site with "synced copy" catalog would sometimes fail creating the catalog
  common/src/main/java/org/broadleafcommerce/common/dao/GenericEntityDaoImpl.java
Labels: type-bug

#2482 Removed "Deprecated" annotation from AdminGroupPresentation#collapsed
  common/src/main/java/org/broadleafcommerce/common/presentation/AdminGroupPresentation.java
Labels: severity-minor, type-bug
