Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2021-06, with the labels that each got.

#2517 Fixed an issue where Sorting for values of BroadleafEnumerationType doesn't work
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BroadleafEnumerationUtility.java
Labels: severity-minor, type-bug

#2516 Upgrade spring-security to address vulnerability
  pom.xml
Labels: type-security

#2492 Add the ability for Products to be Copied
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopier.java
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopyContext.java
  common/src/main/java/org/broadleafcommerce/common/persistence/AbstractEntityDuplicationHelper.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicationHelper.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorExtensionManager.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CategoryProductXrefImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductAttributeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionValueImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionXrefImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuProductOptionValueXrefImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/ProductDuplicateModifier.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferDuplicateModifier.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext.xml
Labels: type-feature

#2500 Adds the ability to create a new entity inside the current folder
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
Labels: type-enhancement

#2505 Adds search capabilities to folder entity list page
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: type-enhancement

#2525 Upgrade libs for security
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/CatalogURLServiceImpl.java
  pom.xml
Labels: type-security

#2527 Added code to properly encode the &laquo; and &raquo; characters
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
Labels: severity-minor, type-bug

#2531 Upgrade libs for security
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/CatalogURLServiceImpl.java
  pom.xml
Labels: type-security

#2530 Add county field
  common/src/main/java/org/broadleafcommerce/common/payment/dto/AddressDTO.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderToPaymentRequestDTOServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/PaymentResponseDTOToEntityServiceImpl.java
Labels: client-gopher, type-enhancement

#2528 upgrade ehcache
  pom.xml
Labels: type-enhancement

#2526 Fixed an issue where Sorting for values of BroadleafEnumerationType doesn't work
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BroadleafEnumerationUtility.java
Labels: severity-minor

#2532 Entity lookups are displaying empty fields when participating in an adornedTargetCollection relationship
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: severity-minor, type-bug

#2529 Fixed ConfirmedPaymentRollbackHandler to make sure to archive all payments if a rollback is triggered
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/workflow/ConfirmPaymentsRollbackHandler.java
Labels: severity-minor, type-bug

#2533 Core changes for Duplicator 6 0
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminOfferController.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminProductController.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/admin/web/controller/AdminAssetUploadController.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminAbstractController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/AdminTranslationController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicEntityController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/controller/entity/AdminBasicOperationsController.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/entity/DefaultEntityFormActions.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/form/entity/EntityFormAction.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopier.java
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopyContext.java
  common/src/main/java/org/broadleafcommerce/common/dao/GenericEntityDaoImpl.java
  common/src/main/java/org/broadleafcommerce/common/persistence/AbstractEntityDuplicationHelper.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicateModifier.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicationHelper.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicator.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorExtensionManager.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityDuplicatorImpl.java
  common/src/test/resources/blc-config/bl-test-applicationContext.xml
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CategoryProductXrefImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductAttributeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionValueImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionXrefImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuProductOptionValueXrefImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/ProductDuplicateModifier.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferDuplicateModifier.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext.xml
Labels: type-enhancement

#2534 Code refactoring for OrderToPaymentRequestDTOServiceImpl
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderToPaymentRequestDTOServiceImpl.java
Labels: type-enhancement

#2538 Upgrade xml bean to latest version
  pom.xml
Labels: type-security

#2537 libs update
  common/src/main/resources/esapi-java-logging.properties
  common/src/main/resources/esapi/ESAPI.properties
  pom.xml
Labels: type-security

#2539 Adding check whether versioning is enabled to drive whether versioning is added to resource file names when bundling is disabled
  common/src/main/java/org/broadleafcommerce/common/web/processor/ResourceBundleProcessor.java
Labels: severity-minor, type-bug
