Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2021-02, with the labels that each got.

#2486 Fixed an issue where Customer updated on registration validation errors
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/account/BroadleafRegisterController.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerDao.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerDaoImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/service/CustomerService.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/service/CustomerServiceImpl.java
Labels: severity-major, type-bug

#2487 Upgrading Apache Commons-Validator library to latest available (version 1.7)
  pom.xml
Labels: type-enhancement

#2489 Disable login user by email
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/user/AdminUserDetailsServiceImpl.java
Labels: severity-minor, type-bug

#2488 Added post fetch verification and foreign key security check
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
Labels: severity-major, type-bug

#2490 - Fix mvel issue when parser fails to parse ?someBeanA || ?someBeanB. ?someBeanB is a valid expression, but parser fails, so need to wrap it in ()
  admin/broadleaf-admin-module/src/test/java/org/broadleafcommerce/admin/web/rulebuilder/DataDTOToMVELTranslatorTest.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/DataDTOToMVELTranslator.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/rulebuilder/MVELToDataWrapperTranslator.java
Labels: type-bug

#2491 Added post fetch verification and foreign key security check
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
Labels: type-bug

#2393 Fixed Spring DataBinder warning
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/translations.js
Labels: type-bug

#2493 Changed access modifier of the post validation method
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
Labels: severity-major, type-bug

#2480 Add sorting back so add to cart addons/checkout process works smooth
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/CartOperationRequest.java
Labels: type-bug

#2444 Added default locale for Site
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityCommon.properties
  common/src/main/java/org/broadleafcommerce/common/site/domain/Site.java
  common/src/main/java/org/broadleafcommerce/common/site/domain/SiteImpl.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafLocaleResolverImpl.java
Labels: type-enhancement
