Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2022-04, with the labels that each got.

#2648 Revisit Recursive Relationships for UpSaleProduct
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/UpSaleProductCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/bl-admin-applicationContext.xml
  admin/broadleaf-admin-module/src/main/resources/messages/UtilityMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: type-bug, severity-critical

#2639 Revisit Recursive Relationships for Category
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/CategoryCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminMessages.properties
Labels: type-bug, severity-critical

#2649 Java calendar starts from 0 for the month so added 1 to make it natural count.
  common/src/main/java/org/broadleafcommerce/common/TimeDTO.java
Labels: type-bug, client-weightwatchers

#2647 Remove inline scripts in scrollbar script so CSP should not react on it
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.mCustomScrollbar.js
Labels: type-bug

#2658 Revisit Recursive Relationships for ChildCategories
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/CategoryCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/ChildCategoriesCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/messages/MerchandisingMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/messages/OpenAdminMessages.properties
Labels: type-bug, severity-major

#2656 Fixed ampersand issue for offer rules
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/RuleFieldExtractionUtility.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/RuleFieldPersistenceProvider.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/AbstractBaseProcessor.java
Labels: type-bug, severity-critical

#2652 Fixed single quote issue for product options values
  common/src/main/resources/esapi/validation.properties
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionValueProcessor.java
Labels: type-bug, severity-critical

#2662 Fix to support non numeric PK which name is not "id"
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/BasicFieldPersistenceProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/request/AddSearchMappingRequest.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: type-bug, severity-minor

#2664 Change the condition to evaluate if classExcludeRegexList is used
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopier.java
Labels: type-enhancement

#2666 Check for duplicate items for CrossSaleProduct
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/CrossSaleProductCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/messages/MerchandisingMessages.properties
Labels: type-bug, severity-major
