Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2022-01, with the labels that each got.

#2620 Javadocs are needing a reference to the javax interceptor binding
  pom.xml
Labels: type-bug

#2621 Upgrade plugin to configure doclint from javadoc's config section.
  pom.xml
Labels: type-enhancement

#2622 Update protobuf version
  common/pom.xml
Labels: type-enhancement

#2623 Change admin references to cdnjs libraries
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/plugins/jquery.mCustomScrollbar.js
Labels: type-enhancement

#2619 In MultiTenantCopier, deprecating direct use of Matcher for regex evaluations and instead using Pattern Matcher. Now using classExcludeRegexPatternList as list of expressions to exclude.
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopier.java
Labels: type-bug, severity-major

#2625 Deprecated redundant concurrency protection in CheckoutServiceImpl
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/CheckoutServiceImpl.java
Labels: type-enhancement

#2626 Parameter in getAntiSamyPolicy
  common/src/main/java/org/broadleafcommerce/common/security/service/ExploitProtectionServiceImpl.java
Labels: type-bug

#2624 Removed redundant concurrency protection in CheckoutServiceImpl
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/CheckoutServiceImpl.java
Labels: type-enhancement

#2632 Cleanup deprecated inventory types
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/rulebuilder/service/options/InventoryTypeEnumOptionsExtensionListener.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/type/InventoryType.java
Labels: type-enhancement

#2634 Partially complete payment status is not calculated correctly
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderPaymentStatusServiceImpl.java
Labels: type-bug, severity-minor

#2628 Prevent duplication of elements in classExcludeRegexPatternList
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopier.java
Labels: type-enhancement

#2636 MultiTenantCopier is using not thread safe Matcher
  common/src/main/java/org/broadleafcommerce/common/copy/MultiTenantCopier.java
Labels: type-bug, severity-major

#2637 Upgrade the core libraries to the latest patch releases
  common/pom.xml
  pom.xml
Labels: type-enhancement
