Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2022-06, with the labels that each got.

#2691 Updated selectize.js and added persist settings
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/selectize.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/selectize.min.js
Labels: type-bug, type-enhancement

#2692 Revert updating selectize.js to the last version
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/selectize.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/selectize.min.js
Labels: type-bug

#2682 Upgraded Spring to 5.2.22 for 6.1
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/domain/StaticAssetImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/dto/PersistencePerspective.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/AdornedTargetCollectionFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/BasicFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/CollectionFieldMetadataProvider.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/MapFieldMetadataProvider.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationAdornedTargetCollectionOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationCollectionOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationDataDrivenEnumerationOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationMapOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationOverride.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationOverrides.java
  common/src/main/java/org/broadleafcommerce/common/presentation/override/AdminPresentationToOneLookupOverride.java
  common/src/main/resources/esapi/ESAPI.properties
  common/src/main/resources/esapi/validation.properties
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchFacetRangeImpl.java
  pom.xml
Labels: type-security

#2696 Renamed property to differentiate by groupId and updated dependencies from sun.xml which now resolves txw2 properly to 2.3.1.
  pom.xml
Labels: type-bug, severity-major
