Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2022-09, with the labels that each got.

#2702 Removed StateImpl bean from context
  core/broadleaf-profile/src/main/resources/META-INF/persistence-profile.xml
  core/broadleaf-profile/src/main/resources/bl-profile-applicationContext-entity.xml
  core/broadleaf-profile/src/main/resources/config/bc/sql/demo/load_code_tables.sql
Labels: type-bug, severity-blocker-dev

#2704 Filter dialog box works correct
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/blc-query-builder.css
Labels: type-bug, client-oreilly

#2720 Update hibernate dialect retrieving. Removed deprecated calls and add Transactional for DialectHelper
  common/src/main/java/org/broadleafcommerce/common/util/DialectHelper.java
Labels: type-bug

#2722 Fixed readOrderById when it couldn't find the order
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
Labels: type-bug

#2705 Fixed an issue where a product with add-ons cannot be added to the cart when their SKU is out of stock
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/UncacheableDataProcessor.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/AbstractInventoryServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/InventoryServiceExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/InventoryServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
Labels: type-bug
