Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2022-08, with the labels that each got.

#2678 Esapi version updated
  common/src/main/resources/esapi-java-logging.properties
  common/src/main/resources/esapi/ESAPI.properties
  pom.xml
Labels: type-bug, type-security

#2709 Antisamy upgraded for security vulnerability
  admin/broadleaf-open-admin-platform/src/main/resources/antisamy-myspace.xml
  pom.xml
Labels: type-security

#2712 QA-4761 - fix dependency vulnerability in broadleaf-open-admin-platform
  admin/broadleaf-open-admin-platform/pom.xml
Labels: ready-for-code-review, dependencies

#2715 Changed inner classes and two fields to protected in ResourcePurgeServiceImpl
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeServiceImpl.java
Labels: type-enhancement

#2716 Impoved logging for SiteMap generation when timeout
  common/src/main/java/org/broadleafcommerce/common/sitemap/service/SiteMapServiceImpl.java
Labels: type-bug

#2710 Order should be read according to its site disc
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
Labels: type-bug, client-flywire
