Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2022-10, with the labels that each got.

#2733 Added restriction for archived sku
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductOptionDaoImpl.java
Labels: type-bug, severity-low, client-biww

#2714 Checkout is not active when product options are not chosen
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/NullOrderImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/Order.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/OrderImpl.java
Labels: type-bug, severity-medium

#2723 Use locale translations for Product Option Values when rendering cart
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionDisplayProcessor.java
Labels: type-bug, severity-minor

#2726 Fixed tooltip for entity (Menu Changes)
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafCurrencyResolverImpl.java
  common/src/main/java/org/broadleafcommerce/common/web/BroadleafRequestProcessor.java
Labels: type-bug

#2732 Changed blJCacheConfigurationBuilder parameters
  common/src/main/java/org/broadleafcommerce/common/extensibility/cache/ehcache/DefaultEhCacheConfigurationBuilder.java
Labels: type-bug, severity-minor

#2728 Fixed SKU generation for the Product Options
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/AdminCatalogServiceImpl.java
Labels: type-bug, severity-minor

#2719 Changed countOfferCodeUses to not use cross join
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/dao/OfferAuditDaoImpl.java
Labels: type-enhancement

#2725 Check if some parent categories of the product active or not
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
Labels: type-bug

#2734 Fix issue when updating qty in cart when default sku for inventory feature is enabled
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/CheckAddAvailabilityActivity.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/CheckUpdateAvailabilityActivity.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext.xml
Labels: type-bug, severity-minor

#2738 Removed Spring mobile dependency
  core/broadleaf-framework-web/pom.xml
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/config/FrameworkWebConfig.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/device/BroadleafDeviceResolverRequestFilter.java
  pom.xml
Labels: type-enhancement

#2741 Added new exclusions for the SandBoxClassTransformer from the new Java versions
  common/src/main/resources/bl-common-applicationContext.xml
Labels: type-bug

#2724 Removed Joda-Time dependency in framework and updated classes to use Java Date/Time
  common/pom.xml
  common/src/main/java/org/broadleafcommerce/common/util/BLCPaymentMethodUtils.java
  common/src/main/java/org/broadleafcommerce/common/util/PomEvaluator.java
  core/broadleaf-framework/pom.xml
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/checkout/service/strategy/OrderPaymentConfirmationStrategyImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/processor/AbstractBaseProcessor.java
  integration/src/test/java/org/broadleafcommerce/core/payment/service/NullIntegrationGatewayTransactionServiceImpl.java
  pom.xml
Labels: type-bug
