Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2022-07, with the labels that each got.

#2699 Exception when filter product bundle add on
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/ProductCustomPersistenceHandler.java
Labels: type-bug, client-weightwatchers

#2690 Fix re-appearing item in offer rules
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/ruleBuilder-v2.js
Labels: type-bug

#2698 Deleted weave logic for default sku
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Product.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/service/InventoryServiceImpl.java
Labels: type-enhancement

#2697 QA-4728-read-customer-by-email-case-insensitive - modify read customer by email query to be case insensitive
  core/broadleaf-profile/src/main/resources/config/bc/jpa/domain/Customer.orm.xml
Labels: type-bug, severity-minor

#2695 Fixed 403 error when page refreshes
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityParentIdServiceExtensionHandler.java
  common/src/main/java/org/broadleafcommerce/common/persistence/EntityParentIdServiceExtensionManager.java
Labels: type-bug, client-icon-fitness, severity-medium

#2703 Added useDefaultSkuForInventory property to methods of Product class
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
Labels: type-bug
