Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-09, with the labels that each got.

#2882 Add hibernate filters for each persistence unit instead of each entity class
  common/src/main/java/org/broadleafcommerce/common/extensibility/jpa/MergePersistenceUnitManager.java
Labels: type-enhancement

#2884 Performance optimization for 7.0 after testing by LoadTest
  common/src/main/java/org/broadleafcommerce/common/i18n/service/TranslationServiceImpl.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/NamedOrderProcessor.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/CustomerOfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/domain/OfferImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/offer/service/OfferServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/RoleDaoImpl.java
Labels: type-enhancement

#2874 Upgrade Solr
  core/broadleaf-framework/pom.xml
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/BroadleafCloudSolrClient.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/DelegatingHttpSolrClient.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrConfiguration.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/index/SolrIndexServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/indexer/SolrIndexUpdateCommandHandler.java
  core/broadleaf-framework/src/main/resources/config/bc/fw/common.properties
  pom.xml
Labels: type-enhancement, severity-major

#2891 Updated logger dependencies
  admin/broadleaf-admin-functional-tests/pom.xml
  common/pom.xml
  core/broadleaf-framework/pom.xml
  integration/pom.xml
  pom.xml
Labels: type-enhancement, severity-minor

#2892 Fix to prevent a user to use his session to manipulate entities in other site (5.2)
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/remote/AdminSecurityServiceRemote.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/filter/BroadleafAdminRequestFilter.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/filter/BroadleafAdminRequestProcessor.java
Labels: type-security

#2889 Update the GEB lib
  admin/broadleaf-admin-functional-tests/src/main/groovy/GebConfig.groovy
  admin/broadleaf-admin-functional-tests/src/main/groovy/org/broadleafcommerce/browsertest/page/TopLevelEntity.groovy
  pom.xml
Labels: type-enhancement

#2897 Fix of error in uploading new assets
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetServiceImpl.java
  pom.xml
Labels: type-bug, severity-major
