Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-05, with the labels that each got.

#2826 Upgrade various libraries for security.
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  common/pom.xml
  pom.xml
Labels: type-security

#2832 Fixed deprecation warning for date format
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: type-bug, severity-minor

#2831 Upgrade moment.js to 2.29.4 version
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/moment-with-locales.min.js
Labels: severity-medium
