Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-04, with the labels that each got.

#2780 Changed modifier from private to protected for ProductOptionValueDTO class
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionValueProcessor.java
Labels: type-enhancement

#2816 Added a regex validation for admin password
  admin/broadleaf-admin-module/src/main/resources/messages/CustomerCareMessages.properties
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminUserImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/AdminRegexValidator.java
  admin/broadleaf-open-admin-platform/src/main/resources/config/bc/admin/common.properties
Labels: type-security

#2815 Introduced whitelist for upload file extensions with property allowed.file.extensions
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/service/StaticAssetServiceImpl.java
  admin/broadleaf-contentmanagement-module/src/main/resources/config/bc/cms/common.properties
  admin/broadleaf-contentmanagement-module/src/test/java/org/broadleafcommerce/cms/file/service/StaticAssetServiceImplTest.java
  admin/broadleaf-contentmanagement-module/src/test/resources/testfile/img.png
  admin/broadleaf-contentmanagement-module/src/test/resources/testfile/text-file.txt
Labels: type-enhancement

#2817 Resolved category cache issues
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CategoryImpl.java
Labels: type-bug, severity-minor

#2802 Production Option Value Translations could not be getting missed now
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionDisplayProcessor.java
Labels: type-bug

#2814 Fixed Integration module tests
  integration/src/test/java/org/broadleafcommerce/test/junit/JUnitAdminIntegrationSetup.java
  integration/src/test/java/org/broadleafcommerce/test/junit/JUnitSiteIntegrationSetup.java
  integration/src/test/java/org/broadleafcommerce/test/junit/JUnitTransactionalAdminIntegrationSetup.java
  integration/src/test/java/org/broadleafcommerce/test/junit/JUnitTransactionalSiteIntegrationSetup.java
  pom.xml
Labels: type-bug

#2818 Added cache annotations to entities
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageFieldImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentFieldImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentFieldXrefImpl.java
Labels: type-bug
