Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-06, with the labels that each got.

#2835 Update version in POMs
  common/pom.xml
  common/src/main/java/org/broadleafcommerce/common/resource/service/GoogleClosureJavascriptMinificationServiceImpl.java
  integration/pom.xml
  pom.xml
Labels: severity-major, type-security

#2828 QA-4975 - add generic selector to find the Media input hidden
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/assetSelector.js
Labels: type-bug, difficulty-easy, ready-for-code-review

#2837 Fix for showing product availability on site
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/UncacheableDataProcessor.java
Labels: type-bug, severity-minor

#2839 Fix for not adding empty(undefined) filter in the end
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: type-bug, severity-minor

#2822 Added filtration for alt skus in case default sku is used to track inventory
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
Labels: type-bug, severity-minor

#2844 Fixes for Addition status purge job
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/AbstractAdditionStatusDaoExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/AdditionStatusDaoExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/AdditionStatusDaoExtensionManager.java
Labels: type-enhancement
