Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-02, with the labels that each got.

#2764 Sku with future pricelist data now don't disappear from the site
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
Labels: type-bug, severity-medium

#2782 Qa 4785 springboot upgrade
  pom.xml
Labels: type-enhancement

#2797 Upgrade antisamy and jackson.
  pom.xml
Labels: type-security

#2779 Fixed alignment on filter button
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/entityForm.css
Labels: type-bug, severity-minor

#2781 Fix Misaligned header in the listgrid
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
Labels: type-bug, severity-minor
