Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-11, with the labels that each got.

#2922 Fixed invalid queries producement if the sandBoxHelper.mergeCloneIds returns multiple rows
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDaoImpl.java
  core/broadleaf-framework/src/main/resources/config/bc/jpa/domain/Product.orm.xml
Labels: type-bug

#2923 Remove some deprecated classes
  common/src/main/java/org/broadleafcommerce/common/util/BLCAnnotationUtils.java
  common/src/main/java/org/broadleafcommerce/common/util/BLResourceBundleMessageSource.java
  common/src/main/java/org/broadleafcommerce/common/util/BroadleafMergeResourceBundleMessageSource.java
  common/src/main/java/org/broadleafcommerce/common/util/ResourceBundleExtensionPoint.java
Labels: type-enhancement

#2926 Upgrade springboot to latest version of 3.1
  pom.xml
Labels: type-enhancement

#2911 Using the Time Zone Setting
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  common/src/main/java/org/broadleafcommerce/common/util/BLCDateUtils.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/DateProcessor.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/ProductDuplicateModifier.java
Labels: type-enhancement, severity-minor

#2913 Preview on site addon error
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/extension/AbstractPreviewProductUrlModifierExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/extension/PreviewProductUrlModifierExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/extension/PreviewProductUrlModifierExtensionManager.java
Labels: type-bug, severity-medium

#2890 Fix for Sandbox clone purge foreign key constraint issues
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/event/AbstractPurgeSandboxClonedEntitiesExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/event/PurgeSandboxClonedEntitiesExtensionHandler.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/event/PurgeSandboxClonedEntitiesExtensionManager.java
Labels: type-enhancement

#2932 Can't view few sections of the admin
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/extension/AbstractPreviewProductUrlModifierExtensionHandler.java
Labels: type-bug
