Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-03, with the labels that each got.

#2800 Fixed Thymeleaf custom tags usages
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/AdminModuleExpression.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/AdminModuleProcessor.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/AdminUserExpression.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/AdminUserProcessor.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/header.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/leftNav.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/secondLeftNav.html
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/NamedOrderExpression.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/NamedOrderProcessor.java
Labels: type-bug

#2803 Cleanup unused Thymeleaf custom processors and refactoring
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/processor/ContentExpression.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/web/processor/ContentProcessor.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/AdminFieldBuilderExpression.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/AdminFieldBuilderProcessor.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/ErrorsExpression.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/ErrorsProcessor.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/ruleBuilder.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
  common/src/main/java/org/broadleafcommerce/common/breadcrumbs/processor/BreadcrumbExpression.java
  common/src/main/java/org/broadleafcommerce/common/breadcrumbs/processor/BreadcrumbProcessor.java
Labels: type-bug

#2804 Cleanup unused Thymeleaf custom processors and refactoring
  common/src/main/java/org/broadleafcommerce/common/web/expression/PropertiesVariableExpression.java
  common/src/main/java/org/broadleafcommerce/common/web/payment/processor/CreditCardTypesExpression.java
  common/src/main/java/org/broadleafcommerce/common/web/payment/processor/CreditCardTypesProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/ConfigVariableProcessor.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/DataDrivenEnumerationExpression.java
  common/src/main/java/org/broadleafcommerce/common/web/processor/DataDrivenEnumerationProcessor.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/CategoriesExpression.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/CategoriesProcessor.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/OnePageCheckoutProcessor.java
Labels: type-bug

#2806 Updated Thymeleaf custom RatingsProcessor
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/RatingsExpression.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/RatingsProcessor.java
Labels: type-bug

#2736 Added checkbox type to 6.3
  admin/broadleaf-admin-module/src/main/resources/admin_style/js/admin/catalog/productOptions.js
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOption.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/type/ProductOptionType.java
Labels: type-enhancement

#2777 Fixes of InaccessibleObjectException with Java 17
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
Labels: type-bug, severity-medium

#2799 Fixing caret position in redactor when switching WYSIWG mode and caret inside style tag
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/lib/redactor.js
Labels: type-bug, severity-minor

#2809 There is a potential use case where the categoryXref::getDefaultReference can be null when filtering out products during a solr catalog search
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
Labels: type-bug, severity-medium

#2813 Invert exception.showstacktrace property usage in AdminMappingExceptionResolver to properly show or not show stacktrace
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/handler/AdminMappingExceptionResolver.java
Labels: type-bug
