Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-12, with the labels that each got.

#2893 Prevent add to the cart non production products
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/workflow/add/ValidateAddRequestActivity.java
Labels: type-bug, severity-minor

#2933 Fixes missing cache [query.CustomerAddress]
  common/src/main/java/org/broadleafcommerce/common/config/CommonCacheConfiguration.java
Labels: type-bug, severity-minor

#2950 Add horizontal scrolling to listgrid
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/listGrid.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid-paginate.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/listGrid.html
Labels: type-enhancement, severity-medium

#2941 Fixed an issue where the discount value was displayed incorrectly
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
Labels: type-bug, severity-major

#2943 Updated version of spring
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  pom.xml
Labels: severity-major, type-security
