Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-01, with the labels that each got.

#2761 Update javadoc for AdminPresentationCollection.friendlyName
  common/src/main/java/org/broadleafcommerce/common/presentation/AdminPresentationCollection.java
Labels: type-enhancement, severity-major

#2752 Updated hibernate to version 5.6.14
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/dao/provider/metadata/MapFieldsFieldMetadataProvider.java
  common/pom.xml
  pom.xml
Labels: type-enhancement

#2749 Fix for customer with null id during checkout
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/controller/checkout/BroadleafCheckoutController.java
Labels: type-bug

#2753 Removed period at end of resource value
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
Labels: type-bug

#2751 make sure that if value is string but metadata is broadleaf enumeration final value will be a friendly type of broadleaf enumeration
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/DefaultFieldPersistenceProvider.java
Labels: type-bug, severity-major, ready-for-code-review

#2748 Improve exception-handling for the CSRF verification flow
  common/src/main/java/org/broadleafcommerce/common/security/handler/CsrfFilter.java
  common/src/main/java/org/broadleafcommerce/common/security/handler/SecurityFilter.java
  common/src/main/java/org/broadleafcommerce/common/security/service/ExploitProtectionServiceImpl.java
Labels: type-enhancement, severity-minor

#2763 Add emailType for blSendAdminResetPasswordEmail and blSendAdminUsernameEmailInfo
  admin/broadleaf-open-admin-platform/src/main/resources/bl-open-admin-contentCreator-applicationContext.xml
Labels: type-bug, severity-minor

#2768 Removing the class level @Transactional annotation as that is causing an excessive number of transactions and JDBC commits
  common/src/main/java/org/broadleafcommerce/common/util/DialectHelper.java
Labels: type-bug, severity-major

#2759 Fixed listGrid boundaries after window resizing
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: type-bug

#2758 Update jquery-ui to version 1.13.2 and momentjs to version 2.29.4 and stylesheet clean up
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/vendor/moment-with-locales.min.js
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/footer.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/head.html
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/loginHead.html
  common/src/main/resources/common_style/css/admin/jquery-ui-1.13.2.custom.css
  common/src/main/resources/common_style/css/jquery-ui-1.13.2.custom.css
  common/src/main/resources/common_style/js/lib/plugins/jquery-ui-1.13.1.custom.js
  common/src/main/resources/common_style/js/lib/plugins/jquery-ui-1.13.2.custom.js
Labels: severity-major, type-security

#2746 Upgraded HSQL version to 2.7.1
  admin/broadleaf-open-admin-platform/pom.xml
  common/pom.xml
  integration/pom.xml
  pom.xml
Labels: type-security

#2769 QA-4885: fixed recursion call of window.resize()
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: type-bug, severity-critical

#2771 Updating spring security version in pom
  pom.xml
Labels: type-enhancement

#2766 Add cache hint to order find by id query
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/dao/OrderDaoImpl.java
Labels: type-enhancement

#2772 Fix alignment of the filter description box
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/entityForm.css
Labels: type-bug, severity-minor

#2775 Fix EntityManager error when using multiple threads in MultiTenant Module
  common/src/main/java/org/broadleafcommerce/common/util/StreamingTransactionCapableUtil.java
Labels: type-bug, severity-minor, ready-for-code-review

#2774 Make PrecoessDetailLogger more extendable, fixed typo
  common/src/main/java/org/broadleafcommerce/common/logging/ProcessDetailLogger.java
Labels: type-enhancement

#2765 Added cleanup method for the Email Tracking DAO
  common/src/main/java/org/broadleafcommerce/common/email/dao/EmailReportingDao.java
  common/src/main/java/org/broadleafcommerce/common/email/dao/EmailReportingDaoImpl.java
  common/src/main/java/org/broadleafcommerce/common/email/domain/EmailTrackingImpl.java
Labels: type-bug

#2773 Validating customer id during customer password reset workflow
  core/broadleaf-profile-web/src/main/java/org/broadleafcommerce/profile/web/core/CustomerStateRefresher.java
Labels: type-bug, severity-minor, ready-for-code-review

#2776 Updating version of jettison, esapi, dependency-check-maven
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
  pom.xml
Labels: type-security, severity-medium
