Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2023-10, with the labels that each got.

#2900 Update resource not to generate 404 error, that is mapped to /error
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/loginHead.html
  pom.xml
Labels: type-security

#2895 Fix for resource bundle issue
  common/src/main/java/org/broadleafcommerce/common/web/processor/AbstractResourceProcessor.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/linkeddata/processor/LinkedDataProcessor.java
Labels: type-bug, severity-medium

#2899 Removed legacy xxx classes
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/AdminCatalogServiceImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldEnumeration.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldEnumerationImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldEnumerationItem.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/field/domain/FieldEnumerationItemImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageTemplate.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageTemplateImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/dao/StructuredContentDao.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContent.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Product.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Sku.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/RelatedProductsServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/legacy/LegacyCartService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/legacy/LegacyCartServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/legacy/LegacyMergeCartServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/legacy/LegacyOrderService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/legacy/LegacyOrderServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/strategy/FulfillmentGroupItemStrategyImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/pricing/service/workflow/AutoBundleActivity.java
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-persistence.xml
  integration/src/test/java/org/broadleafcommerce/core/catalog/dao/ProductDaoTest.java
  integration/src/test/java/org/broadleafcommerce/core/catalog/service/CatalogTest.java
  integration/src/test/java/org/broadleafcommerce/core/order/service/OrderBaseTest.java
  integration/src/test/java/org/broadleafcommerce/test/CommonSetupBaseTest.java
Labels: type-enhancement, severity-minor

#2902 Remove FieldEnumerationImpl and FieldEnumerationItemImpl from persistence-cms.xml
  admin/broadleaf-contentmanagement-module/src/main/resources/META-INF/persistence-cms.xml
Labels: type-bug

#2896 Upgrade snappy-java to 1.1.10.4 version
  pom.xml
Labels: type-security

#2906 Revert removing getter and setter for skuMedia
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/Sku.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuImpl.java
Labels: type-enhancement

#2912 Improve hashCode method for the ProductImpl
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
Labels: type-enhancement

#2917 Upgrade Ecma script version for closure compiler
  common/src/main/resources/config/bc/common.properties
Labels: type-enhancement

#2918 Final patch upgrades for before ga release for 7.0
  core/broadleaf-framework/src/test/groovy/org/broadleafcommerce/core/spec/offer/service/workflow/RecordOfferUsageRollbackHandlerSpec.groovy
  integration/pom.xml
  integration/src/test/java/org/broadleafcommerce/core/order/service/OrderTest.java
  pom.xml
Labels: type-enhancement, severity-medium

#2919 move static invocation from template into "VariableExpression"
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/expression/ServletRequestVariableExpression.java
Labels: type-bug
