Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2024-05, with the labels that each got.

#2998 Add to the ProductOptionsProcessor an AddOn handling
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionsExpression.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionsProcessor.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/ProductOptionsProcessorExtensionHandler.java
Labels: type-bug

#3001 Fixes the issue where url parameter is empty
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/blc-admin-history.js
  common/src/main/resources/common_style/js/BLC.js
Labels: type-bug, severity-major

#3002 Add validation to avoid Orphaned Offer Code records
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCodeCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/messages/UtilityMessages.properties
Labels: type-bug

#3003 Addition Status Purge Job and Sandbox Cloned Entities Purge Job changes
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/util/service/ResourcePurgeServiceImpl.java
Labels: type-enhancement

#3004 Add validation of the value in offer
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/messages/MerchandisingMessages.properties
Labels: type-enhancement

#3006 Fixes of ESAPI configure error
  common/src/main/resources/esapi-java-logging.properties
Labels: type-bug, severity-major
