Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2024-03, with the labels that each got.

#2972 Fixes the issue where it was showing old popup when created new entity
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/BasicPersistenceModule.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/module/provider/MediaFieldPersistenceProvider.java
Labels: type-bug, severity-major

#2969 WIP: Removing the use of deprecated methods from BroadleafCommerce
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/domain/StaticAssetImpl.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/CategoryDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/CategoryDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/dao/ProductDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOption.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/CatalogService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/CatalogServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/dynamic/DefaultDynamicSkuPricingServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/dynamic/DynamicSkuPricingService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/dao/OrderPaymentDao.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/dao/OrderPaymentDaoImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/domain/PaymentLog.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/domain/PaymentLogImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderPaymentService.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/service/OrderPaymentServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceImpl.java
  core/broadleaf-framework/src/main/resources/META-INF/persistence-framework.xml
  core/broadleaf-framework/src/main/resources/bl-framework-applicationContext-entity.xml
Labels: type-enhancement, severity-minor

#2977 Fixed an issue where Entity header disappears after reload the product page
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: type-bug, severity-minor

#2978 Fixed model in the FormProcessor
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/FormProcessor.java
Labels: type-bug

#2975 Fixes the issue where it was showing incorrect placement of error message
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/css/admin/entityForm.css
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/entityForm.js
Labels: type-enhancement, severity-minor

#2973 Adding checking of regex property to RegexPropertyValidator
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/persistence/validation/ProductBundleSkuBundleItemValidator.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/RegexPropertyValidator.java
Labels: type-bug, severity-minor
