Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2024-01, with the labels that each got.

#2955 Fixes for incorrect display of filter values in search
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: type-bug, severity-major

#2947 Added check for double request parameter
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/search/SearchRequestWrapper.java
  core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/search/SearchUrlFilter.java
  core/broadleaf-framework/src/main/resources/config/bc/fw/common.properties
Labels: type-enhancement, severity-minor

#2942 Fixed Security vulnerability for ESAPI
  pom.xml
Labels: type-bug, type-security

#2939 Changing the display logic of the entityForm title
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/entityTitle.html
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/service/ProductDuplicateModifier.java
Labels: type-bug, severity-minor

#2934 WIP: Fix deprecated @Index annotation
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/domain/StaticAsset.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/domain/StaticAssetImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/file/domain/StaticAssetStorageImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageAttributeImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminModuleImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminSectionImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminUserAttributeImpl.java
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/domain/AdminUserImpl.java
  common/src/main/java/org/broadleafcommerce/common/presentation/AdminPresentation.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CategoryAttributeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CategoryImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/CrossSaleProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/FeaturedProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductAttributeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/SkuAttributeImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/UpSaleProductImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/inventory/domain/SkuAvailabilityImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/domain/FulfillmentGroupImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchInterceptImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/domain/SearchSynonymImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/redirect/domain/SearchRedirectImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrSearchServiceExtensionHandler.java
Labels: type-enhancement, severity-minor

#2956 Fixes in the display logic of the entityForm title
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/entityTitle.html
Labels: type-bug, severity-minor

#2958 Fixing checkForMatches logic to find the regEx rows only and not to iterate through all URLHandlers
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/url/service/URLHandlerServiceImpl.java
  admin/broadleaf-contentmanagement-module/src/test/java/org/broadleafcommerce/cms/url/service/URLHandlerServiceTest.java
Labels: type-bug, severity-medium

#2952 Prevent generating too many skus
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/AdminCatalogService.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/AdminCatalogServiceImpl.java
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/action/AdminCatalogActionsController.java
  admin/broadleaf-admin-module/src/main/resources/messages/UtilityMessages.properties
  admin/broadleaf-open-admin-platform/src/main/resources/config/bc/admin/common.properties
Labels: type-enhancement, severity-minor
