Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2025-01, with the labels that each got.

#3035 Fixed join column mapping
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/page/domain/PageImpl.java
  admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
Labels: type-bug

#3037 Fix for the issue when Registered customer cannot remove address from address book
  core/broadleaf-profile/src/main/java/org/broadleafcommerce/profile/core/dao/CustomerAddressDaoImpl.java
Labels: type-bug, severity-major

#3036 Custom upgrade to java 17
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/security/service/navigation/AdminNavigationServiceImpl.java
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderServiceImpl.java
Labels: severity-major

#3040 Fix for the issue when Error is not displayed when adding a subcollection entity
  admin/broadleaf-admin-module/src/main/resources/messages/UtilityMessages.properties
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/processor/ErrorsProcessor.java
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/components/entityForm.html
Labels: type-bug, severity-major

#3041 Adding validation before adding an SKU manually
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
  admin/broadleaf-admin-module/src/main/resources/messages/MerchandisingMessages.properties
Labels: type-enhancement, severity-minor
