Repository BroadleafCommerce/BroadleafCommerce, pull requests merged in 2025-02, with the labels that each got.

#3047 Fixed an issue where Too many skus to generate error message does not appear for moved product options
  admin/broadleaf-admin-module/src/main/resources/admin_style/js/admin/catalog/product.js
  admin/broadleaf-admin-module/src/main/resources/messages/MerchandisingMessages.properties
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionImpl.java
Labels: type-bug, severity-minor

#3046 Fixed an issue where Indexed Fields filtering does not work
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/web/controller/entity/AdminFieldController.java
Labels: type-bug, severity-minor

#3048 Fixed an issue with successful SKU generation message
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/listGrid.js
Labels: type-bug, severity-minor

#3053 Add Mockito package to DirectCopyIgnorePattern
  common/src/main/resources/bl-common-applicationContext.xml
Labels: type-enhancement

#3054 Fix for the issue the Empty Listgrid Filter visual bug
  admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/js/admin/components/filterbuilder.js
Labels: type-bug

#3044 Fixed an issue where some parts of code would remain un-renamed.
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
  admin/broadleaf-open-admin-platform/src/main/resources/messages/GeneratedMessagesEntityFramework.properties
  core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductImpl.java
Labels: type-bug, severity-minor

#3039 Generate metadata in SKU only for product options with skuGeneration=true
  admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/SkuCustomPersistenceHandler.java
Labels: type-bug

#3049 Added decoding for the list grid tooltip item
  admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
Labels: type-bug
